/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_onnxmlir_OMModel */

#ifndef _Included_com_ibm_onnxmlir_OMModel
#define _Included_com_ibm_onnxmlir_OMModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_onnxmlir_OMModel
 * Method:    main_graph_jni
 * Signature: (Lcom/ibm/onnxmlir/OMTensorList;)Lcom/ibm/onnxmlir/OMTensorList;
 */
JNIEXPORT jobject JNICALL Java_com_ibm_onnxmlir_OMModel_main_1graph_1jni(
    JNIEnv *, jclass, jobject);

/*
 * Class:     com_ibm_onnxmlir_OMModel
 * Method:    input_signature_jni
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ibm_onnxmlir_OMModel_input_1signature_1jni(
    JNIEnv *, jclass, jstring);

/*
 * Class:     com_ibm_onnxmlir_OMModel
 * Method:    output_signature_jni
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ibm_onnxmlir_OMModel_output_1signature_1jni(
    JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
