/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_onnxmlir_DynEntryPoint */

#ifndef _Included_com_ibm_onnxmlir_DynEntryPoint
#define _Included_com_ibm_onnxmlir_DynEntryPoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_onnxmlir_DynEntryPoint
 * Method:    main_graph_jni
 * Signature: (Lcom/ibm/onnxmlir/OrderedRtMemRefDict;)Lcom/ibm/onnxmlir/OrderedRtMemRefDict;
 */
JNIEXPORT jobject JNICALL Java_com_ibm_onnxmlir_DynEntryPoint_main_1graph_1jni
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
