"""Read .npy files saved by run-torch.py and return their contents as numpy arrays."""

import numpy as np
import sys
import time


def read_npy_files(filenames):
    """Read a list of .npy files and return a dict mapping filename to numpy array.

    Args:
        filenames: list of .npy file paths to read.

    Returns:
        List of np.array read from .npy file.
    """
    arrays = []
    for path in filenames:
        arr = np.load(path)
        # Convert the data for endian
        arrays.append(arr.astype(arr.dtype.newbyteorder("=")))
    return arrays


"""Utility to compare two lists of numpy arrays (reference vs actual)."""
"""Generated by Bob."""


def compare_result_bob(actual, reference, atol=1e-8, rtol=1e-5):
    """Compare two lists of numpy arrays element by element.

    Parameters
    ----------
    actual : list of np.ndarray
        Actual arrays to check.
    reference : list of np.ndarray
        Expected arrays.
    atol : float
        Absolute tolerance for floating-point comparison.
    rtol : float
        Relative tolerance for floating-point comparison.

    Returns
    -------
    bool
        True if all arrays match within the given tolerances.
    """
    if len(reference) != len(actual):
        print(
            f"FAIL: list length mismatch: reference={len(reference)}, actual={len(actual)}"
        )
        return False

    all_pass = True
    for i, (ref, act) in enumerate(zip(reference, actual)):
        if ref.shape != act.shape:
            print(
                f"FAIL: output[{i}] shape mismatch: reference={ref.shape}, actual={act.shape}"
            )
            all_pass = False
            continue

        if ref.dtype != act.dtype:
            print(
                f"FAIL: output[{i}] dtype mismatch: reference={ref.dtype}, actual={act.dtype}"
            )
            all_pass = False
            continue

        if np.issubdtype(ref.dtype, np.integer):
            if not np.array_equal(ref, act):
                diff_count = int(np.count_nonzero(ref != act))
                print(
                    f"FAIL: output[{i}] (integer) has {diff_count} mismatched elements"
                )
                all_pass = False
            else:
                print(f"PASS: output[{i}] (integer) shape={ref.shape} exact match")
        elif np.issubdtype(ref.dtype, np.floating):
            if np.allclose(ref, act, rtol=rtol, atol=atol):
                print(
                    f"PASS: output[{i}] (float) shape={ref.shape} within rtol={rtol}, atol={atol}"
                )
            else:
                abs_diff = np.abs(ref - act)
                max_abs = float(np.max(abs_diff))
                # Avoid division by zero for relative diff
                denom = np.maximum(np.abs(ref), 1e-30)
                max_rel = float(np.max(abs_diff / denom))
                diff_count = int(
                    np.count_nonzero(~np.isclose(ref, act, rtol=rtol, atol=atol))
                )
                print(
                    f"FAIL: output[{i}] (float) shape={ref.shape} "
                    f"max_abs_diff={max_abs:.6e}, max_rel_diff={max_rel:.6e}, "
                    f"mismatched={diff_count}/{ref.size}"
                    f"comparison parameter atol = {atol} rtol = {rtol}"
                )
                all_pass = False
        else:
            # Fall back to exact comparison for other dtypes (bool, etc.)
            if np.array_equal(ref, act):
                print(
                    f"PASS: output[{i}] dtype={ref.dtype} shape={ref.shape} exact match"
                )
            else:
                diff_count = int(np.count_nonzero(ref != act))
                print(
                    f"FAIL: output[{i}] dtype={ref.dtype} has {diff_count} mismatched elements"
                )
                all_pass = False

    return all_pass


"""
This is the implementation from RunONNXModel.py.
The major difference is that the atol and rtol is combined in comparison.
diff = float(atol) + float(rtol) * abs(ref_val)
"""


def compare_result(actual_outs, ref_outs, atol=1e-8, rtol=1e-5, debug=0):
    total_elements = 0
    mismatched_elements = 0
    max_atol = 0
    sum_rtol = 0
    # The outputs are of shape: #queries, seq_length, hidden_states, with
    # seq_length various with query.
    for q_index in range(len(actual_outs)):
        q_actual_outs = actual_outs[q_index]
        q_ref_outs = ref_outs[q_index]
        for index, actual_val in np.ndenumerate(q_actual_outs):
            total_elements += 1
            ref_val = q_ref_outs[index]
            this_atol = abs(ref_val - actual_val)
            max_atol = max(this_atol, max_atol)
            sum_rtol += abs((this_atol) / ref_val)
            if np.issubdtype(q_actual_outs.dtype, np.dtype(bool).type):
                if ref_val == actual_val:
                    continue
            else:
                # Use equation atol + rtol * abs(desired), that is used in assert_allclose.
                diff = float(atol) + float(rtol) * abs(ref_val)
                if abs(actual_val - ref_val) <= diff:
                    continue
            mismatched_elements += 1
            if debug >= 1:
                print(
                    "  at {}".format(index),
                    "mismatch {} (actual)".format(actual_val),
                    "vs {} (reference)".format(ref_val),
                )

    print(
        f"Max absolute difference: {max_atol}\nMean of relative difference {sum_rtol/total_elements}"
    )
    print(f"Under the requirement of atol {atol} and rtol {rtol}")
    if mismatched_elements == 0:
        print("\n✓ correct.\n")
        return True
    else:
        print(
            "\n✗  got mismatched elements {}/{}, in percentage {}.\n".format(
                mismatched_elements,
                total_elements,
                mismatched_elements / total_elements,
            )
        )
        return False


def ordinal(n):
    suffix = ["th", "st", "nd", "rd", "th"][min(n % 10, 4)]
    if 11 <= (n % 100) <= 13:
        suffix = "th"
    return str(n) + suffix


def data_without_top_bottom_quartile(data, percent):
    data = np.array(sorted(data))
    trim = int(percent * data.size / 100.0)
    if trim == 0 or data.size - 2 * trim < 1:
        # Want at least one element, return as is.
        return data
    return data[trim:-trim]


def process_perf_results(perf_results):
    # Print statistics info, e.g., min/max/stddev inference time.
    print(
        "  Statistics 1 (excluding warmup),"
        " min, {:.6e}, max, {:.6e}, mean, {:.6e}, stdev, {:.6e}".format(
            np.min(perf_results),
            np.max(perf_results),
            np.mean(perf_results),
            np.std(perf_results, dtype=np.float64),
        )
    )
    t_perf_results = data_without_top_bottom_quartile(perf_results, 25)
    print(
        "  Statistics 2 (no warmup/quart.),"
        " min, {:.6e}, max, {:.6e}, mean, {:.6e}, stdev, {:.6e}".format(
            np.min(t_perf_results),
            np.max(t_perf_results),
            np.mean(t_perf_results),
            np.std(t_perf_results, dtype=np.float64),
        )
    )


def run_model_with_file(
    session,
    input_files,
    ref_output_files=None,
    warmup=0,
    repeat=1,
    debug=0,
    atol=0.1,
    rtol=0.05,
):
    input_arrays = read_npy_files(input_files)

    try:
        for i in range(warmup):
            outputs = session.run(input_arrays, debug)
    except Exception as e:
        print(f"Inference {i} got exception: {e}")
        sys.exit(-1)

    perf_results = []
    for i in range(repeat):
        start = time.perf_counter()
        outputs = session.run(input_arrays)
        end = time.perf_counter()
        elapsed = end - start
        perf_results += [elapsed]
        print("  {} iteration, {}, seconds".format(ordinal(i + 1), elapsed))
    if repeat > 1:
        process_perf_results(perf_results)

    if ref_output_files:
        ref_outputs = read_npy_files(ref_output_files)
        all_match = compare_result(outputs, ref_outputs, atol, rtol)

        # Not sure whether to continue becuase the numerical difference
        # does not necessarily mean failure for end-to-end
        if not all_match:
            sys.exit(-1)

    return outputs
