ARG BASE_IMAGE
FROM ${BASE_IMAGE} AS onnx-mlir-dev-test

# Label the base image so it can be cleaned up after becoming dangling
ARG ONNX_MLIR_PR_NUMBER
ARG ONNX_MLIR_PR_NUMBER2
LABEL onnx_mlir_pr_number=${ONNX_MLIR_PR_NUMBER}
LABEL onnx_mlir_pr_number2=${ONNX_MLIR_PR_NUMBER2}

ARG WORK_DIR=/workdir
WORKDIR ${WORK_DIR}

# Copy onnx-mlir from the pull request
COPY . onnx-mlir

# Setup onnx
#ARG THIRD_PARTY_ONNX_SHA1=b2a20a9d07678e89ae9346243035e194b63e0e8a
#RUN pip3 install git+git://github.com/onnx/onnx.git@${THIRD_PARTY_ONNX_SHA1} \
#    && rm -rf /root/.cache
RUN ONNX_ROOT=${WORK_DIR}/onnx-mlir/third_party/onnx \
    && cd ${ONNX_ROOT} \
    && python3 setup.py -q install \
    && rm -rf .eggs .setuptools-cmake-build build dist onnx.egg-info

RUN LLVM_PROJECT_ROOT=${WORK_DIR}/llvm-project \
    && ONNX_MLIR_ROOT=${WORK_DIR}/onnx-mlir \
# Build onnx-mlir and run tests
    && cd ${ONNX_MLIR_ROOT} \
    && rm -rf build && mkdir -p build && cd build \
    && LLVM_PROJ_SRC=${LLVM_PROJECT_ROOT} \
       LLVM_PROJ_BUILD=${LLVM_PROJECT_ROOT}/build \
       cmake .. \
    && make -j$(nproc) \
    # && LIT_OPTS=-v make -j$(nproc) check-onnx-lit \
    && make check-onnx-backend \
    && make check-onnx-backend-dynamic \
    && make ARGS=-j$(nproc) test \
    # && make check-doc \
    && make onnx-mlir-doc \
    && rm -rf /tmp/*

# Copy from onnx-mlir-dev-test to squash removed source layer and
# remove dependency on base image (onnx-mlir-llvm-static)
FROM scratch

ARG WORK_DIR=/workdir
WORKDIR ${WORK_DIR}

# Label the images for various checking and cleanup
ARG ONNX_MLIR_SHA1
ARG ONNX_MLIR_SHA1_DATE
ARG ONNX_MLIR_DOCKERFILE_SHA1
ARG ONNX_MLIR_PR_NUMBER
ARG ONNX_MLIR_PR_NUMBER2
LABEL onnx_mlir_sha1=${ONNX_MLIR_SHA1}
LABEL onnx_mlir_sha1_date=${ONNX_MLIR_SHA1_DATE}
LABEL onnx_mlir_dockerfile_sha1=${ONNX_MLIR_DOCKERFILE_SHA1}
LABEL onnx_mlir_pr_number=${ONNX_MLIR_PR_NUMBER}
LABEL onnx_mlir_pr_number2=${ONNX_MLIR_PR_NUMBER2}

COPY --from=onnx-mlir-dev-test / /
CMD [ "/bin/bash" ]
