// Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
// RUN: onnx-mlir-opt -split-input-file --recompose-onnx --canonicalize %s | FileCheck %s

func.func @decomposition_to_layernorm_axis_1(%arg0: tensor<1x4x128x128xf32>) -> tensor<1x4x128x128xf32> {
  %2 = onnx.Constant dense<1.000000e+00> : tensor<f32>
  %4 = onnx.Constant dense<9.99999997E-7> : tensor<f32>
  %5 = onnx.Constant dense<[[[0.0970484465]], [[0.0882187337]], [[0.135120019]], [[0.14907673]]]> : tensor<4x1x1xf32>
  %6 = onnx.Constant dense<[[[0.191972837]], [[0.286264896]], [[0.180535644]], [[0.166878015]]]> : tensor<4x1x1xf32>    
  %9 = "onnx.ReduceMeanV13"(%arg0) {axes = [1], keepdims = 1 : si64, onnx_node_name = "/mask_downscaling/mask_downscaling.1/ReduceMean"} : (tensor<1x4x128x128xf32>) -> tensor<1x1x128x128xf32>
  %10 = "onnx.Sub"(%arg0, %9) {onnx_node_name = "/mask_downscaling/mask_downscaling.1/Sub"} : (tensor<1x4x128x128xf32>, tensor<1x1x128x128xf32>) -> tensor<1x4x128x128xf32>
  %11 = "onnx.Mul"(%10, %10) {onnx_node_name = "/mask_downscaling/mask_downscaling.1/Pow_1"} : (tensor<1x4x128x128xf32>, tensor<1x4x128x128xf32>) -> tensor<1x4x128x128xf32>
  %12 = "onnx.ReduceMeanV13"(%11) {axes = [1], keepdims = 1 : si64, onnx_node_name = "/mask_downscaling/mask_downscaling.1/ReduceMean_1"} : (tensor<1x4x128x128xf32>) -> tensor<1x1x128x128xf32>
  %13 = "onnx.Add"(%12, %4) {onnx_node_name = "/mask_downscaling/mask_downscaling.1/Add"} : (tensor<1x1x128x128xf32>, tensor<f32>) -> tensor<1x1x128x128xf32>
  %14 = "onnx.Sqrt"(%13) {onnx_node_name = "/mask_downscaling/mask_downscaling.1/Sqrt"} : (tensor<1x1x128x128xf32>) -> tensor<1x1x128x128xf32>
  %15 = "onnx.Div"(%10, %14) {onnx_node_name = "/mask_downscaling/mask_downscaling.1/Div"} : (tensor<1x4x128x128xf32>, tensor<1x1x128x128xf32>) -> tensor<1x4x128x128xf32>
  %16 = "onnx.Mul"(%15, %5) {onnx_node_name = "/mask_downscaling/mask_downscaling.1/Mul_2"} : (tensor<1x4x128x128xf32>, tensor<4x1x1xf32>) -> tensor<1x4x128x128xf32>
  %17 = "onnx.Add"(%16, %6) {onnx_node_name = "/mask_downscaling/mask_downscaling.1/Add_1"} : (tensor<1x4x128x128xf32>, tensor<4x1x1xf32>) -> tensor<1x4x128x128xf32>
  return %17 : tensor<1x4x128x128xf32>
}
// CHECK-LABEL:  func.func @decomposition_to_layernorm_axis_1
// CHECK-SAME:   ([[PARAM_0_:%.+]]: tensor<1x4x128x128xf32>) -> tensor<1x4x128x128xf32> {
// CHECK-DAG:       [[VAR_0_:%.+]] = onnx.Constant dense<{{.}}{{.}}[0.0970484465]{{.}}, {{.}}[0.0882187337]{{.}}, {{.}}[0.135120019]{{.}}, {{.}}[0.14907673]{{.}}{{.}}> : tensor<4x1x1xf32>
// CHECK-DAG:       [[VAR_1_:%.+]] = onnx.Constant dense<{{.}}{{.}}[0.191972837]{{.}}, {{.}}[0.286264896]{{.}}, {{.}}[0.180535644]{{.}}, {{.}}[0.166878015]{{.}}{{.}}> : tensor<4x1x1xf32>
// CHECK-DAG:       [[VAR_2_:%.+]] = onnx.Constant dense<[1, 4, 1, 1]> : tensor<4xi64>
// CHECK-DAG:       [[VAR_3_:%.+]] = "onnx.Reshape"([[VAR_0_]], [[VAR_2_]]) {allowzero = 0 : si64} : (tensor<4x1x1xf32>, tensor<4xi64>) -> tensor<1x4x1x1xf32>
// CHECK-DAG:       [[VAR_4_:%.+]] = "onnx.Transpose"([[VAR_3_]]) {perm = [0, 2, 3, 1]} : (tensor<1x4x1x1xf32>) -> tensor<1x1x1x4xf32>
// CHECK-DAG:       [[VAR_5_:%.+]] = "onnx.Transpose"([[PARAM_0_]]) {perm = [0, 2, 3, 1]} : (tensor<1x4x128x128xf32>) -> tensor<1x128x128x4xf32>
// CHECK-DAG:       [[VAR_6_:%.+]] = "onnx.Reshape"([[VAR_1_]], [[VAR_2_]]) {allowzero = 0 : si64} : (tensor<4x1x1xf32>, tensor<4xi64>) -> tensor<1x4x1x1xf32>
// CHECK-DAG:       [[VAR_7_:%.+]] = "onnx.Transpose"([[VAR_6_]]) {perm = [0, 2, 3, 1]} : (tensor<1x4x1x1xf32>) -> tensor<1x1x1x4xf32>
// CHECK-DAG:       [[VAR_Y_:%.+]], [[VAR_Mean_:%.+]], [[VAR_InvStdDev_:%.+]] = "onnx.LayerNormalization"([[VAR_5_]], [[VAR_4_]], [[VAR_7_]]) {axis = 3 : si64, epsilon = 9.99999997E-7 : f32, stash_type = 1 : si64} : (tensor<1x128x128x4xf32>, tensor<1x1x1x4xf32>, tensor<1x1x1x4xf32>) -> (tensor<1x128x128x4xf32>, none, none)
// CHECK-DAG:       [[VAR_8_:%.+]] = "onnx.Transpose"([[VAR_Y_]]) {perm = [0, 3, 1, 2]} : (tensor<1x128x128x4xf32>) -> tensor<1x4x128x128xf32>
// CHECK:           return [[VAR_8_]] : tensor<1x4x128x128xf32>
// CHECK:         }

// -----

func.func @decomposition_to_layernorm_axis_2(%arg0: tensor<1x128x4x128xf32> {onnx.name = "in0"}) -> (tensor<1x128x4x128xf32> {onnx.name = "out"}) {
  %0 = onnx.Constant dense<[[[0.976699769], [0.380195737], [0.923246204], [0.261692435]]]> : tensor<1x4x1xf32>
  %1 = onnx.Constant dense<9.99999997E-7> : tensor<f32>
  %2 = onnx.Constant dense<2> : tensor<1xi64>
  %3 = "onnx.ReduceMean"(%arg0, %2) {keepdims = 1 : si64, noop_with_empty_axes = 0 : si64, onnx_node_name = "ReduceMean1"} : (tensor<1x128x4x128xf32>, tensor<1xi64>) -> tensor<1x128x1x128xf32>
  %4 = "onnx.Sub"(%arg0, %3) {onnx_node_name = "Sub2"} : (tensor<1x128x4x128xf32>, tensor<1x128x1x128xf32>) -> tensor<1x128x4x128xf32>
  %5 = "onnx.Mul"(%4, %4) {onnx_node_name = "Mul3"} : (tensor<1x128x4x128xf32>, tensor<1x128x4x128xf32>) -> tensor<1x128x4x128xf32>
  %6 = "onnx.ReduceMean"(%5, %2) {keepdims = 1 : si64, noop_with_empty_axes = 0 : si64, onnx_node_name = "ReduceMean4"} : (tensor<1x128x4x128xf32>, tensor<1xi64>) -> tensor<1x128x1x128xf32>
  %7 = "onnx.Add"(%6, %1) {onnx_node_name = "Add6"} : (tensor<1x128x1x128xf32>, tensor<f32>) -> tensor<1x128x1x128xf32>
  %8 = "onnx.Sqrt"(%7) {onnx_node_name = "Sqrt7"} : (tensor<1x128x1x128xf32>) -> tensor<1x128x1x128xf32>
  %9 = "onnx.Div"(%4, %8) {onnx_node_name = "Div8"} : (tensor<1x128x4x128xf32>, tensor<1x128x1x128xf32>) -> tensor<1x128x4x128xf32>
  %10 = "onnx.Mul"(%0, %9) {onnx_node_name = "Mul10"} : (tensor<1x4x1xf32>, tensor<1x128x4x128xf32>) -> tensor<1x128x4x128xf32>
  %11 = "onnx.Add"(%10, %0) {onnx_node_name = "Add12"} : (tensor<1x128x4x128xf32>, tensor<1x4x1xf32>) -> tensor<1x128x4x128xf32>
  onnx.Return %11 : tensor<1x128x4x128xf32>
}
// CHECK-LABEL:  func.func @decomposition_to_layernorm_axis_2
// CHECK-SAME:   ([[PARAM_0_:%.+]]: tensor<1x128x4x128xf32> {onnx.name = "in0"}) -> (tensor<1x128x4x128xf32> {onnx.name = "out"}) {
// CHECK-DAG:       [[VAR_0_:%.+]] = onnx.Constant dense<{{.}}{{.}}[0.976699769], [0.380195737], [0.923246204], [0.261692435]{{.}}{{.}}> : tensor<1x4x1xf32>
// CHECK-DAG:       [[VAR_1_:%.+]] = onnx.Constant dense<[1, 1, 4, 1]> : tensor<4xi64>
// CHECK-DAG:       [[VAR_2_:%.+]] = "onnx.Reshape"([[VAR_0_]], [[VAR_1_]]) {allowzero = 0 : si64} : (tensor<1x4x1xf32>, tensor<4xi64>) -> tensor<1x1x4x1xf32>
// CHECK-DAG:       [[VAR_3_:%.+]] = "onnx.Transpose"([[VAR_2_]]) {perm = [0, 1, 3, 2]} : (tensor<1x1x4x1xf32>) -> tensor<1x1x1x4xf32>
// CHECK-DAG:       [[VAR_4_:%.+]] = "onnx.Transpose"([[PARAM_0_]]) {perm = [0, 1, 3, 2]} : (tensor<1x128x4x128xf32>) -> tensor<1x128x128x4xf32>
// CHECK-DAG:       [[VAR_5_:%.+]] = "onnx.Reshape"([[VAR_0_]], [[VAR_1_]]) {allowzero = 0 : si64} : (tensor<1x4x1xf32>, tensor<4xi64>) -> tensor<1x1x4x1xf32>
// CHECK-DAG:       [[VAR_6_:%.+]] = "onnx.Transpose"([[VAR_5_]]) {perm = [0, 1, 3, 2]} : (tensor<1x1x4x1xf32>) -> tensor<1x1x1x4xf32>
// CHECK-DAG:       [[VAR_Y_:%.+]], [[VAR_Mean_:%.+]], [[VAR_InvStdDev_:%.+]] = "onnx.LayerNormalization"([[VAR_4_]], [[VAR_3_]], [[VAR_6_]]) {axis = 3 : si64, epsilon = 9.99999997E-7 : f32, stash_type = 1 : si64} : (tensor<1x128x128x4xf32>, tensor<1x1x1x4xf32>, tensor<1x1x1x4xf32>) -> (tensor<1x128x128x4xf32>, none, none)
// CHECK-DAG:       [[VAR_7_:%.+]] = "onnx.Transpose"([[VAR_Y_]]) {perm = [0, 1, 3, 2]} : (tensor<1x128x128x4xf32>) -> tensor<1x128x4x128xf32>
// CHECK:           onnx.Return [[VAR_7_]] : tensor<1x128x4x128xf32>
// CHECK:         }

// -----

func.func @decomposition_to_layernorm_axis_1_and_2(%arg0: tensor<1x4x128x128xf32> {onnx.name = "in0"}) -> (tensor<1x4x128x128xf32> {onnx.name = "out"}) {
  %0 = onnx.Constant dense<[[[0.976699769]], [[0.380195737]], [[0.923246204]], [[0.261692435]]]> : tensor<4x1x1xf32>
  %1 = onnx.Constant dense<9.99999997E-7> : tensor<f32>
  %2 = onnx.Constant dense<[1, 2]> : tensor<2xi64>
  %3 = "onnx.ReduceMean"(%arg0, %2) {keepdims = 1 : si64, noop_with_empty_axes = 0 : si64, onnx_node_name = "ReduceMean1"} : (tensor<1x4x128x128xf32>, tensor<2xi64>) -> tensor<1x1x1x128xf32>
  %4 = "onnx.Sub"(%arg0, %3) {onnx_node_name = "Sub2"} : (tensor<1x4x128x128xf32>, tensor<1x1x1x128xf32>) -> tensor<1x4x128x128xf32>
  %5 = "onnx.Mul"(%4, %4) {onnx_node_name = "Mul3"} : (tensor<1x4x128x128xf32>, tensor<1x4x128x128xf32>) -> tensor<1x4x128x128xf32>
  %6 = "onnx.ReduceMean"(%5, %2) {keepdims = 1 : si64, noop_with_empty_axes = 0 : si64, onnx_node_name = "ReduceMean4"} : (tensor<1x4x128x128xf32>, tensor<2xi64>) -> tensor<1x1x1x128xf32>
  %7 = "onnx.Add"(%6, %1) {onnx_node_name = "Add6"} : (tensor<1x1x1x128xf32>, tensor<f32>) -> tensor<1x1x1x128xf32>
  %8 = "onnx.Sqrt"(%7) {onnx_node_name = "Sqrt7"} : (tensor<1x1x1x128xf32>) -> tensor<1x1x1x128xf32>
  %9 = "onnx.Div"(%4, %8) {onnx_node_name = "Div8"} : (tensor<1x4x128x128xf32>, tensor<1x1x1x128xf32>) -> tensor<1x4x128x128xf32>
  %10 = "onnx.Mul"(%0, %9) {onnx_node_name = "Mul10"} : (tensor<4x1x1xf32>, tensor<1x4x128x128xf32>) -> tensor<1x4x128x128xf32>
  %11 = "onnx.Add"(%10, %0) {onnx_node_name = "Add12"} : (tensor<1x4x128x128xf32>, tensor<4x1x1xf32>) -> tensor<1x4x128x128xf32>
  onnx.Return %11 : tensor<1x4x128x128xf32>
}
// CHECK-LABEL:  func.func @decomposition_to_layernorm_axis_1_and_2
// CHECK-SAME:   ([[PARAM_0_:%.+]]: tensor<1x4x128x128xf32> {onnx.name = "in0"}) -> (tensor<1x4x128x128xf32> {onnx.name = "out"}) {
// CHECK-DAG:       [[VAR_0_:%.+]] = onnx.Constant dense<{{.}}{{.}}[0.976699769]{{.}}, {{.}}[0.380195737]{{.}}, {{.}}[0.923246204]{{.}}, {{.}}[0.261692435]{{.}}{{.}}> : tensor<4x1x1xf32>
// CHECK-DAG:       [[VAR_1_:%.+]] = onnx.Constant dense<[1, 4, 1, 1]> : tensor<4xi64>
// CHECK-DAG:       [[VAR_2_:%.+]] = "onnx.Reshape"([[VAR_0_]], [[VAR_1_]]) {allowzero = 0 : si64} : (tensor<4x1x1xf32>, tensor<4xi64>) -> tensor<1x4x1x1xf32>
// CHECK-DAG:       [[VAR_3_:%.+]] = "onnx.Transpose"([[VAR_2_]]) {perm = [0, 3, 1, 2]} : (tensor<1x4x1x1xf32>) -> tensor<1x1x4x1xf32>
// CHECK-DAG:       [[VAR_4_:%.+]] = "onnx.Transpose"([[PARAM_0_]]) {perm = [0, 3, 1, 2]} : (tensor<1x4x128x128xf32>) -> tensor<1x128x4x128xf32>
// CHECK-DAG:       [[VAR_5_:%.+]] = "onnx.Reshape"([[VAR_0_]], [[VAR_1_]]) {allowzero = 0 : si64} : (tensor<4x1x1xf32>, tensor<4xi64>) -> tensor<1x4x1x1xf32>
// CHECK-DAG:       [[VAR_6_:%.+]] = "onnx.Transpose"([[VAR_5_]]) {perm = [0, 3, 1, 2]} : (tensor<1x4x1x1xf32>) -> tensor<1x1x4x1xf32>
// CHECK-DAG:       [[VAR_Y_:%.+]], [[VAR_Mean_:%.+]], [[VAR_InvStdDev_:%.+]] = "onnx.LayerNormalization"([[VAR_4_]], [[VAR_3_]], [[VAR_6_]]) {axis = 2 : si64, epsilon = 9.99999997E-7 : f32, stash_type = 1 : si64} : (tensor<1x128x4x128xf32>, tensor<1x1x4x1xf32>, tensor<1x1x4x1xf32>) -> (tensor<1x128x4x128xf32>, none, none)
// CHECK-DAG:       [[VAR_7_:%.+]] = "onnx.Transpose"([[VAR_Y_]]) {perm = [0, 2, 3, 1]} : (tensor<1x128x4x128xf32>) -> tensor<1x4x128x128xf32>
// CHECK:           onnx.Return [[VAR_7_]] : tensor<1x4x128x128xf32>
// CHECK:         }

// -----

func.func @decomposition_to_layernorm_axis_1_and_3(%arg0: tensor<1x4x128x128xf32> {onnx.name = "in0"}) -> (tensor<1x4x128x128xf32> {onnx.name = "out"}) {
  %0 = onnx.Constant dense<[[[0.976699769]], [[0.380195737]], [[0.923246204]], [[0.261692435]]]> : tensor<4x1x1xf32>
  %1 = onnx.Constant dense<9.99999997E-7> : tensor<f32>
  %2 = onnx.Constant dense<[1, 3]> : tensor<2xi64>
  %3 = "onnx.ReduceMean"(%arg0, %2) {keepdims = 1 : si64, noop_with_empty_axes = 0 : si64, onnx_node_name = "ReduceMean1"} : (tensor<1x4x128x128xf32>, tensor<2xi64>) -> tensor<1x1x128x1xf32>
  %4 = "onnx.Sub"(%arg0, %3) {onnx_node_name = "Sub2"} : (tensor<1x4x128x128xf32>, tensor<1x1x128x1xf32>) -> tensor<1x4x128x128xf32>
  %5 = "onnx.Mul"(%4, %4) {onnx_node_name = "Mul3"} : (tensor<1x4x128x128xf32>, tensor<1x4x128x128xf32>) -> tensor<1x4x128x128xf32>
  %6 = "onnx.ReduceMean"(%5, %2) {keepdims = 1 : si64, noop_with_empty_axes = 0 : si64, onnx_node_name = "ReduceMean4"} : (tensor<1x4x128x128xf32>, tensor<2xi64>) -> tensor<1x1x128x1xf32>
  %7 = "onnx.Add"(%6, %1) {onnx_node_name = "Add6"} : (tensor<1x1x128x1xf32>, tensor<f32>) -> tensor<1x1x128x1xf32>
  %8 = "onnx.Sqrt"(%7) {onnx_node_name = "Sqrt7"} : (tensor<1x1x128x1xf32>) -> tensor<1x1x128x1xf32>
  %9 = "onnx.Div"(%4, %8) {onnx_node_name = "Div8"} : (tensor<1x4x128x128xf32>, tensor<1x1x128x1xf32>) -> tensor<1x4x128x128xf32>
  %10 = "onnx.Mul"(%0, %9) {onnx_node_name = "Mul10"} : (tensor<4x1x1xf32>, tensor<1x4x128x128xf32>) -> tensor<1x4x128x128xf32>
  %11 = "onnx.Add"(%10, %0) {onnx_node_name = "Add12"} : (tensor<1x4x128x128xf32>, tensor<4x1x1xf32>) -> tensor<1x4x128x128xf32>
  onnx.Return %11 : tensor<1x4x128x128xf32>
}
// CHECK-LABEL:  func.func @decomposition_to_layernorm_axis_1_and_3
// CHECK-SAME:   ([[PARAM_0_:%.+]]: tensor<1x4x128x128xf32> {onnx.name = "in0"}) -> (tensor<1x4x128x128xf32> {onnx.name = "out"}) {
// CHECK-DAG:       [[VAR_0_:%.+]] = onnx.Constant dense<{{.}}{{.}}[0.976699769]{{.}}, {{.}}[0.380195737]{{.}}, {{.}}[0.923246204]{{.}}, {{.}}[0.261692435]{{.}}{{.}}> : tensor<4x1x1xf32>
// CHECK-DAG:       [[VAR_1_:%.+]] = onnx.Constant dense<[1, 4, 1, 1]> : tensor<4xi64>
// CHECK-DAG:       [[VAR_2_:%.+]] = "onnx.Reshape"([[VAR_0_]], [[VAR_1_]]) {allowzero = 0 : si64} : (tensor<4x1x1xf32>, tensor<4xi64>) -> tensor<1x4x1x1xf32>
// CHECK-DAG:       [[VAR_3_:%.+]] = "onnx.Transpose"([[VAR_2_]]) {perm = [0, 2, 1, 3]} : (tensor<1x4x1x1xf32>) -> tensor<1x1x4x1xf32>
// CHECK-DAG:       [[VAR_4_:%.+]] = "onnx.Transpose"([[PARAM_0_]]) {perm = [0, 2, 1, 3]} : (tensor<1x4x128x128xf32>) -> tensor<1x128x4x128xf32>
// CHECK-DAG:       [[VAR_5_:%.+]] = "onnx.Reshape"([[VAR_0_]], [[VAR_1_]]) {allowzero = 0 : si64} : (tensor<4x1x1xf32>, tensor<4xi64>) -> tensor<1x4x1x1xf32>
// CHECK-DAG:       [[VAR_6_:%.+]] = "onnx.Transpose"([[VAR_5_]]) {perm = [0, 2, 1, 3]} : (tensor<1x4x1x1xf32>) -> tensor<1x1x4x1xf32>
// CHECK-DAG:       [[VAR_Y_:%.+]], [[VAR_Mean_:%.+]], [[VAR_InvStdDev_:%.+]] = "onnx.LayerNormalization"([[VAR_4_]], [[VAR_3_]], [[VAR_6_]]) {axis = 2 : si64, epsilon = 9.99999997E-7 : f32, stash_type = 1 : si64} : (tensor<1x128x4x128xf32>, tensor<1x1x4x1xf32>, tensor<1x1x4x1xf32>) -> (tensor<1x128x4x128xf32>, none, none)
// CHECK-DAG:       [[VAR_7_:%.+]] = "onnx.Transpose"([[VAR_Y_]]) {perm = [0, 2, 1, 3]} : (tensor<1x128x4x128xf32>) -> tensor<1x4x128x128xf32>
// CHECK:           onnx.Return [[VAR_7_]] : tensor<1x4x128x128xf32>
// CHECK:         }

// -----
// these are the exact same test cases as above but already partly recomposed to test the transpose pushing

func.func @partly_decomposition_to_layernorm_axis_1(%arg0: tensor<1x4x128x128xf32>) -> tensor<1x4x128x128xf32> {
  %0 = onnx.Constant dense<1.000000e+00> : tensor<4xf32>
  %1 = onnx.Constant dense<[[[0.0970484465]], [[0.0882187337]], [[0.135120019]], [[0.14907673]]]> : tensor<4x1x1xf32>
  %2 = onnx.Constant dense<[[[0.191972837]], [[0.286264896]], [[0.180535644]], [[0.166878015]]]> : tensor<4x1x1xf32>
  %3 = "onnx.NoValue"() {value} : () -> none
  %4 = "onnx.Transpose"(%arg0) {perm = [0, 2, 3, 1]} : (tensor<1x4x128x128xf32>) -> tensor<1x128x128x4xf32>
  %Y, %Mean, %InvStdDev = "onnx.LayerNormalization"(%4, %0, %3) {axis = 3 : si64, epsilon = 9.99999997E-7 : f32, stash_type = 1 : si64} : (tensor<1x128x128x4xf32>, tensor<4xf32>, none) -> (tensor<1x128x128x4xf32>, none, none)
  %5 = "onnx.Transpose"(%Y) {perm = [0, 3, 1, 2]} : (tensor<1x128x128x4xf32>) -> tensor<1x4x128x128xf32>
  %6 = "onnx.Mul"(%5, %1) {onnx_node_name = "/mask_downscaling/mask_downscaling.1/Mul_2"} : (tensor<1x4x128x128xf32>, tensor<4x1x1xf32>) -> tensor<1x4x128x128xf32>
  %7 = "onnx.Add"(%6, %2) {onnx_node_name = "/mask_downscaling/mask_downscaling.1/Add_1"} : (tensor<1x4x128x128xf32>, tensor<4x1x1xf32>) -> tensor<1x4x128x128xf32>
  return %7 : tensor<1x4x128x128xf32>
}
// CHECK-LABEL:  func.func @partly_decomposition_to_layernorm_axis_1
// CHECK-SAME:   ([[PARAM_0_:%.+]]: tensor<1x4x128x128xf32>) -> tensor<1x4x128x128xf32> {
// CHECK-DAG:       [[VAR_0_:%.+]] = onnx.Constant dense<{{.}}{{.}}[0.0970484465]{{.}}, {{.}}[0.0882187337]{{.}}, {{.}}[0.135120019]{{.}}, {{.}}[0.14907673]{{.}}{{.}}> : tensor<4x1x1xf32>
// CHECK-DAG:       [[VAR_1_:%.+]] = onnx.Constant dense<{{.}}{{.}}[0.191972837]{{.}}, {{.}}[0.286264896]{{.}}, {{.}}[0.180535644]{{.}}, {{.}}[0.166878015]{{.}}{{.}}> : tensor<4x1x1xf32>
// CHECK-DAG:       [[VAR_2_:%.+]] = onnx.Constant dense<[1, 4, 1, 1]> : tensor<4xi64>
// CHECK-DAG:       [[VAR_3_:%.+]] = "onnx.Reshape"([[VAR_0_]], [[VAR_2_]]) {allowzero = 0 : si64} : (tensor<4x1x1xf32>, tensor<4xi64>) -> tensor<1x4x1x1xf32>
// CHECK-DAG:       [[VAR_4_:%.+]] = "onnx.Transpose"([[VAR_3_]]) {perm = [0, 2, 3, 1]} : (tensor<1x4x1x1xf32>) -> tensor<1x1x1x4xf32>
// CHECK-DAG:       [[VAR_5_:%.+]] = "onnx.Transpose"([[PARAM_0_]]) {perm = [0, 2, 3, 1]} : (tensor<1x4x128x128xf32>) -> tensor<1x128x128x4xf32>
// CHECK-DAG:       [[VAR_6_:%.+]] = "onnx.Reshape"([[VAR_1_]], [[VAR_2_]]) {allowzero = 0 : si64} : (tensor<4x1x1xf32>, tensor<4xi64>) -> tensor<1x4x1x1xf32>
// CHECK-DAG:       [[VAR_7_:%.+]] = "onnx.Transpose"([[VAR_6_]]) {perm = [0, 2, 3, 1]} : (tensor<1x4x1x1xf32>) -> tensor<1x1x1x4xf32>
// CHECK-DAG:       [[VAR_Y_:%.+]], [[VAR_Mean_:%.+]], [[VAR_InvStdDev_:%.+]] = "onnx.LayerNormalization"([[VAR_5_]], [[VAR_4_]], [[VAR_7_]]) {axis = 3 : si64, epsilon = 9.99999997E-7 : f32, stash_type = 1 : si64} : (tensor<1x128x128x4xf32>, tensor<1x1x1x4xf32>, tensor<1x1x1x4xf32>) -> (tensor<1x128x128x4xf32>, none, none)
// CHECK-DAG:       [[VAR_8_:%.+]] = "onnx.Transpose"([[VAR_Y_]]) {perm = [0, 3, 1, 2]} : (tensor<1x128x128x4xf32>) -> tensor<1x4x128x128xf32>
// CHECK:           return [[VAR_8_]] : tensor<1x4x128x128xf32>
// CHECK:         }

// -----

func.func @partly_decomposition_to_layernorm_axis_2(%arg0: tensor<1x128x4x128xf32> {onnx.name = "in0"}) -> (tensor<1x128x4x128xf32> {onnx.name = "out"}) {
  %0 = onnx.Constant dense<1.000000e+00> : tensor<4xf32>
  %1 = onnx.Constant dense<[[[0.976699769], [0.380195737], [0.923246204], [0.261692435]]]> : tensor<1x4x1xf32>
  %2 = "onnx.NoValue"() {value} : () -> none
  %3 = "onnx.Transpose"(%arg0) {perm = [0, 1, 3, 2]} : (tensor<1x128x4x128xf32>) -> tensor<1x128x128x4xf32>
  %Y, %Mean, %InvStdDev = "onnx.LayerNormalization"(%3, %0, %2) {axis = 3 : si64, epsilon = 9.99999997E-7 : f32, stash_type = 1 : si64} : (tensor<1x128x128x4xf32>, tensor<4xf32>, none) -> (tensor<1x128x128x4xf32>, none, none)
  %4 = "onnx.Transpose"(%Y) {perm = [0, 1, 3, 2]} : (tensor<1x128x128x4xf32>) -> tensor<1x128x4x128xf32>
  %5 = "onnx.Mul"(%4, %1) : (tensor<1x128x4x128xf32>, tensor<1x4x1xf32>) -> tensor<1x128x4x128xf32>
  %6 = "onnx.Add"(%5, %1) {onnx_node_name = "Add12"} : (tensor<1x128x4x128xf32>, tensor<1x4x1xf32>) -> tensor<1x128x4x128xf32>
  onnx.Return %6 : tensor<1x128x4x128xf32>
}
// CHECK-LABEL:  func.func @partly_decomposition_to_layernorm_axis_2
// CHECK-SAME:   ([[PARAM_0_:%.+]]: tensor<1x128x4x128xf32> {onnx.name = "in0"}) -> (tensor<1x128x4x128xf32> {onnx.name = "out"}) {
// CHECK-DAG:       [[VAR_0_:%.+]] = onnx.Constant dense<{{.}}{{.}}[0.976699769], [0.380195737], [0.923246204], [0.261692435]{{.}}{{.}}> : tensor<1x4x1xf32>
// CHECK-DAG:       [[VAR_1_:%.+]] = onnx.Constant dense<[1, 1, 4, 1]> : tensor<4xi64>
// CHECK-DAG:       [[VAR_2_:%.+]] = "onnx.Reshape"([[VAR_0_]], [[VAR_1_]]) {allowzero = 0 : si64} : (tensor<1x4x1xf32>, tensor<4xi64>) -> tensor<1x1x4x1xf32>
// CHECK-DAG:       [[VAR_3_:%.+]] = "onnx.Transpose"([[VAR_2_]]) {perm = [0, 1, 3, 2]} : (tensor<1x1x4x1xf32>) -> tensor<1x1x1x4xf32>
// CHECK-DAG:       [[VAR_4_:%.+]] = "onnx.Transpose"([[PARAM_0_]]) {perm = [0, 1, 3, 2]} : (tensor<1x128x4x128xf32>) -> tensor<1x128x128x4xf32>
// CHECK-DAG:       [[VAR_5_:%.+]] = "onnx.Reshape"([[VAR_0_]], [[VAR_1_]]) {allowzero = 0 : si64} : (tensor<1x4x1xf32>, tensor<4xi64>) -> tensor<1x1x4x1xf32>
// CHECK-DAG:       [[VAR_6_:%.+]] = "onnx.Transpose"([[VAR_5_]]) {perm = [0, 1, 3, 2]} : (tensor<1x1x4x1xf32>) -> tensor<1x1x1x4xf32>
// CHECK-DAG:       [[VAR_Y_:%.+]], [[VAR_Mean_:%.+]], [[VAR_InvStdDev_:%.+]] = "onnx.LayerNormalization"([[VAR_4_]], [[VAR_3_]], [[VAR_6_]]) {axis = 3 : si64, epsilon = 9.99999997E-7 : f32, stash_type = 1 : si64} : (tensor<1x128x128x4xf32>, tensor<1x1x1x4xf32>, tensor<1x1x1x4xf32>) -> (tensor<1x128x128x4xf32>, none, none)
// CHECK-DAG:       [[VAR_7_:%.+]] = "onnx.Transpose"([[VAR_Y_]]) {perm = [0, 1, 3, 2]} : (tensor<1x128x128x4xf32>) -> tensor<1x128x4x128xf32>
// CHECK:           onnx.Return [[VAR_7_]] : tensor<1x128x4x128xf32>
// CHECK:         }

// -----

func.func @partly_decomposition_to_layernorm_axis_1_and_2(%arg0: tensor<1x4x128x128xf32> {onnx.name = "in0"}) -> (tensor<1x4x128x128xf32> {onnx.name = "out"}) {
  %0 = onnx.Constant dense<1.000000e+00> : tensor<128xf32>
  %1 = onnx.Constant dense<[[[0.976699769]], [[0.380195737]], [[0.923246204]], [[0.261692435]]]> : tensor<4x1x1xf32>
  %2 = "onnx.NoValue"() {value} : () -> none
  %3 = "onnx.Transpose"(%arg0) {perm = [0, 3, 1, 2]} : (tensor<1x4x128x128xf32>) -> tensor<1x128x4x128xf32>
  %Y, %Mean, %InvStdDev = "onnx.LayerNormalization"(%3, %0, %2) {axis = 2 : si64, epsilon = 9.99999997E-7 : f32, stash_type = 1 : si64} : (tensor<1x128x4x128xf32>, tensor<128xf32>, none) -> (tensor<1x128x4x128xf32>, none, none)
  %4 = "onnx.Transpose"(%Y) {perm = [0, 2, 3, 1]} : (tensor<1x128x4x128xf32>) -> tensor<1x4x128x128xf32>
  %5 = "onnx.Mul"(%4, %1) : (tensor<1x4x128x128xf32>, tensor<4x1x1xf32>) -> tensor<1x4x128x128xf32>
  %6 = "onnx.Add"(%5, %1) {onnx_node_name = "Add12"} : (tensor<1x4x128x128xf32>, tensor<4x1x1xf32>) -> tensor<1x4x128x128xf32>
  onnx.Return %6 : tensor<1x4x128x128xf32>
}
// CHECK-LABEL:  func.func @partly_decomposition_to_layernorm_axis_1_and_2
// CHECK-SAME:   ([[PARAM_0_:%.+]]: tensor<1x4x128x128xf32> {onnx.name = "in0"}) -> (tensor<1x4x128x128xf32> {onnx.name = "out"}) {
// CHECK-DAG:       [[VAR_0_:%.+]] = onnx.Constant dense<{{.}}{{.}}[0.976699769]{{.}}, {{.}}[0.380195737]{{.}}, {{.}}[0.923246204]{{.}}, {{.}}[0.261692435]{{.}}{{.}}> : tensor<4x1x1xf32>
// CHECK-DAG:       [[VAR_1_:%.+]] = onnx.Constant dense<[1, 4, 1, 1]> : tensor<4xi64>
// CHECK-DAG:       [[VAR_2_:%.+]] = "onnx.Reshape"([[VAR_0_]], [[VAR_1_]]) {allowzero = 0 : si64} : (tensor<4x1x1xf32>, tensor<4xi64>) -> tensor<1x4x1x1xf32>
// CHECK-DAG:       [[VAR_3_:%.+]] = "onnx.Transpose"([[VAR_2_]]) {perm = [0, 3, 1, 2]} : (tensor<1x4x1x1xf32>) -> tensor<1x1x4x1xf32>
// CHECK-DAG:       [[VAR_4_:%.+]] = "onnx.Transpose"([[PARAM_0_]]) {perm = [0, 3, 1, 2]} : (tensor<1x4x128x128xf32>) -> tensor<1x128x4x128xf32>
// CHECK-DAG:       [[VAR_5_:%.+]] = "onnx.Reshape"([[VAR_0_]], [[VAR_1_]]) {allowzero = 0 : si64} : (tensor<4x1x1xf32>, tensor<4xi64>) -> tensor<1x4x1x1xf32>
// CHECK-DAG:       [[VAR_6_:%.+]] = "onnx.Transpose"([[VAR_5_]]) {perm = [0, 3, 1, 2]} : (tensor<1x4x1x1xf32>) -> tensor<1x1x4x1xf32>
// CHECK-DAG:       [[VAR_Y_:%.+]], [[VAR_Mean_:%.+]], [[VAR_InvStdDev_:%.+]] = "onnx.LayerNormalization"([[VAR_4_]], [[VAR_3_]], [[VAR_6_]]) {axis = 2 : si64, epsilon = 9.99999997E-7 : f32, stash_type = 1 : si64} : (tensor<1x128x4x128xf32>, tensor<1x1x4x1xf32>, tensor<1x1x4x1xf32>) -> (tensor<1x128x4x128xf32>, none, none)
// CHECK-DAG:       [[VAR_7_:%.+]] = "onnx.Transpose"([[VAR_Y_]]) {perm = [0, 2, 3, 1]} : (tensor<1x128x4x128xf32>) -> tensor<1x4x128x128xf32>
// CHECK:           onnx.Return [[VAR_7_]] : tensor<1x4x128x128xf32>
// CHECK:         }

// -----

func.func @partly_decomposition_to_layernorm_axis_1_and_3(%arg0: tensor<1x4x128x128xf32> {onnx.name = "in0"}) -> (tensor<1x4x128x128xf32> {onnx.name = "out"}) {
  %0 = onnx.Constant dense<1.000000e+00> : tensor<128xf32>
  %1 = onnx.Constant dense<[[[0.976699769]], [[0.380195737]], [[0.923246204]], [[0.261692435]]]> : tensor<4x1x1xf32>
  %2 = "onnx.NoValue"() {value} : () -> none
  %3 = "onnx.Transpose"(%arg0) {perm = [0, 2, 1, 3]} : (tensor<1x4x128x128xf32>) -> tensor<1x128x4x128xf32>
  %Y, %Mean, %InvStdDev = "onnx.LayerNormalization"(%3, %0, %2) {axis = 2 : si64, epsilon = 9.99999997E-7 : f32, stash_type = 1 : si64} : (tensor<1x128x4x128xf32>, tensor<128xf32>, none) -> (tensor<1x128x4x128xf32>, none, none)
  %4 = "onnx.Transpose"(%Y) {perm = [0, 2, 1, 3]} : (tensor<1x128x4x128xf32>) -> tensor<1x4x128x128xf32>
  %5 = "onnx.Mul"(%4, %1) : (tensor<1x4x128x128xf32>, tensor<4x1x1xf32>) -> tensor<1x4x128x128xf32>
  %6 = "onnx.Add"(%5, %1) {onnx_node_name = "Add12"} : (tensor<1x4x128x128xf32>, tensor<4x1x1xf32>) -> tensor<1x4x128x128xf32>
  onnx.Return %6 : tensor<1x4x128x128xf32>
}
// CHECK-LABEL:  func.func @partly_decomposition_to_layernorm_axis_1_and_3
// CHECK-SAME:   ([[PARAM_0_:%.+]]: tensor<1x4x128x128xf32> {onnx.name = "in0"}) -> (tensor<1x4x128x128xf32> {onnx.name = "out"}) {
// CHECK-DAG:       [[VAR_0_:%.+]] = onnx.Constant dense<{{.}}{{.}}[0.976699769]{{.}}, {{.}}[0.380195737]{{.}}, {{.}}[0.923246204]{{.}}, {{.}}[0.261692435]{{.}}{{.}}> : tensor<4x1x1xf32>
// CHECK-DAG:       [[VAR_1_:%.+]] = onnx.Constant dense<[1, 4, 1, 1]> : tensor<4xi64>
// CHECK-DAG:       [[VAR_2_:%.+]] = "onnx.Reshape"([[VAR_0_]], [[VAR_1_]]) {allowzero = 0 : si64} : (tensor<4x1x1xf32>, tensor<4xi64>) -> tensor<1x4x1x1xf32>
// CHECK-DAG:       [[VAR_3_:%.+]] = "onnx.Transpose"([[VAR_2_]]) {perm = [0, 2, 1, 3]} : (tensor<1x4x1x1xf32>) -> tensor<1x1x4x1xf32>
// CHECK-DAG:       [[VAR_4_:%.+]] = "onnx.Transpose"([[PARAM_0_]]) {perm = [0, 2, 1, 3]} : (tensor<1x4x128x128xf32>) -> tensor<1x128x4x128xf32>
// CHECK-DAG:       [[VAR_5_:%.+]] = "onnx.Reshape"([[VAR_0_]], [[VAR_1_]]) {allowzero = 0 : si64} : (tensor<4x1x1xf32>, tensor<4xi64>) -> tensor<1x4x1x1xf32>
// CHECK-DAG:       [[VAR_6_:%.+]] = "onnx.Transpose"([[VAR_5_]]) {perm = [0, 2, 1, 3]} : (tensor<1x4x1x1xf32>) -> tensor<1x1x4x1xf32>
// CHECK-DAG:       [[VAR_Y_:%.+]], [[VAR_Mean_:%.+]], [[VAR_InvStdDev_:%.+]] = "onnx.LayerNormalization"([[VAR_4_]], [[VAR_3_]], [[VAR_6_]]) {axis = 2 : si64, epsilon = 9.99999997E-7 : f32, stash_type = 1 : si64} : (tensor<1x128x4x128xf32>, tensor<1x1x4x1xf32>, tensor<1x1x4x1xf32>) -> (tensor<1x128x4x128xf32>, none, none)
// CHECK-DAG:       [[VAR_7_:%.+]] = "onnx.Transpose"([[VAR_Y_]]) {perm = [0, 2, 1, 3]} : (tensor<1x128x4x128xf32>) -> tensor<1x4x128x128xf32>
// CHECK:           onnx.Return [[VAR_7_]] : tensor<1x4x128x128xf32>
// CHECK:         }

// -----

func.func @partly_decomposition_to_layernorm_non_constant_mul(%arg0: tensor<1x4x128x128xf32> {onnx.name = "in0"}, %arg1: tensor<4x1x1xf32>) -> (tensor<1x4x128x128xf32> {onnx.name = "out"}) {
  %0 = onnx.Constant dense<1.000000e+00> : tensor<128xf32>
  %1 = onnx.Constant dense<[[[0.976699769]], [[0.380195737]], [[0.923246204]], [[0.261692435]]]> : tensor<4x1x1xf32>
  %2 = "onnx.NoValue"() {value} : () -> none
  %3 = "onnx.Transpose"(%arg0) {perm = [0, 2, 1, 3]} : (tensor<1x4x128x128xf32>) -> tensor<1x128x4x128xf32>
  %Y, %Mean, %InvStdDev = "onnx.LayerNormalization"(%3, %0, %2) {axis = 2 : si64, epsilon = 9.99999997E-7 : f32, stash_type = 1 : si64} : (tensor<1x128x4x128xf32>, tensor<128xf32>, none) -> (tensor<1x128x4x128xf32>, none, none)
  %4 = "onnx.Transpose"(%Y) {perm = [0, 2, 1, 3]} : (tensor<1x128x4x128xf32>) -> tensor<1x4x128x128xf32>
  %5 = "onnx.Mul"(%4, %arg1) : (tensor<1x4x128x128xf32>, tensor<4x1x1xf32>) -> tensor<1x4x128x128xf32>
  %6 = "onnx.Add"(%5, %1) {onnx_node_name = "Add12"} : (tensor<1x4x128x128xf32>, tensor<4x1x1xf32>) -> tensor<1x4x128x128xf32>
  onnx.Return %6 : tensor<1x4x128x128xf32>
}
// CHECK-LABEL:  func.func @partly_decomposition_to_layernorm_non_constant_mul
// CHECK-SAME:   ([[PARAM_0_:%.+]]: tensor<1x4x128x128xf32> {{.*}}, [[PARAM_1_:%.+]]: tensor<4x1x1xf32>)
// CHECK:           "onnx.LayerNormalization"
// CHECK:           [[VAR_T_:%.+]] = "onnx.Transpose"
// CHECK:           "onnx.Mul"([[VAR_T_]], [[PARAM_1_]]) : (tensor<1x4x128x128xf32>, tensor<4x1x1xf32>)

// -----

func.func @decomposition_to_layernorm_axis_1_f16(%arg0: tensor<1x4x8x8xf16>) -> tensor<1x4x8x8xf16> {
  %eps = onnx.Constant dense<9.99999997E-7> : tensor<f16>
  %scale = onnx.Constant dense<[[[1.000000e+00]], [[2.000000e+00]], [[3.000000e+00]], [[4.000000e+00]]]> : tensor<4x1x1xf16>
  %bias = onnx.Constant dense<[[[0.125000e+00]], [[0.250000e+00]], [[0.375000e+00]], [[0.500000e+00]]]> : tensor<4x1x1xf16>
  %mean = "onnx.ReduceMeanV13"(%arg0) {axes = [1], keepdims = 1 : si64} : (tensor<1x4x8x8xf16>) -> tensor<1x1x8x8xf16>
  %d = "onnx.Sub"(%arg0, %mean) : (tensor<1x4x8x8xf16>, tensor<1x1x8x8xf16>) -> tensor<1x4x8x8xf16>
  %dd = "onnx.Mul"(%d, %d) : (tensor<1x4x8x8xf16>, tensor<1x4x8x8xf16>) -> tensor<1x4x8x8xf16>
  %var = "onnx.ReduceMeanV13"(%dd) {axes = [1], keepdims = 1 : si64} : (tensor<1x4x8x8xf16>) -> tensor<1x1x8x8xf16>
  %varEps = "onnx.Add"(%var, %eps) : (tensor<1x1x8x8xf16>, tensor<f16>) -> tensor<1x1x8x8xf16>
  %stdDev = "onnx.Sqrt"(%varEps) : (tensor<1x1x8x8xf16>) -> tensor<1x1x8x8xf16>
  %norm = "onnx.Div"(%d, %stdDev) : (tensor<1x4x8x8xf16>, tensor<1x1x8x8xf16>) -> tensor<1x4x8x8xf16>
  %normScaled = "onnx.Mul"(%norm, %scale) : (tensor<1x4x8x8xf16>, tensor<4x1x1xf16>) -> tensor<1x4x8x8xf16>
  %y = "onnx.Add"(%normScaled, %bias) : (tensor<1x4x8x8xf16>, tensor<4x1x1xf16>) -> tensor<1x4x8x8xf16>
  return %y : tensor<1x4x8x8xf16>
}
// CHECK-LABEL:  func.func @decomposition_to_layernorm_axis_1_f16
// CHECK-SAME:   ([[PARAM_0_:%.+]]: tensor<1x4x8x8xf16>) -> tensor<1x4x8x8xf16> {
// CHECK-DAG:       [[VAR_0_:%.+]] = onnx.Constant {{.*}} : tensor<4x1x1xf16>
// CHECK-DAG:       [[VAR_1_:%.+]] = onnx.Constant {{.*}} : tensor<4x1x1xf16>
// CHECK-DAG:       [[VAR_2_:%.+]] = onnx.Constant dense<[1, 4, 1, 1]> : tensor<4xi64>
// CHECK-DAG:       [[VAR_3_:%.+]] = "onnx.Reshape"([[VAR_0_]], [[VAR_2_]]) {allowzero = 0 : si64} : (tensor<4x1x1xf16>, tensor<4xi64>) -> tensor<1x4x1x1xf16>
// CHECK-DAG:       [[VAR_4_:%.+]] = "onnx.Transpose"([[VAR_3_]]) {perm = [0, 2, 3, 1]} : (tensor<1x4x1x1xf16>) -> tensor<1x1x1x4xf16>
// CHECK-DAG:       [[VAR_5_:%.+]] = "onnx.Transpose"([[PARAM_0_]]) {perm = [0, 2, 3, 1]} : (tensor<1x4x8x8xf16>) -> tensor<1x8x8x4xf16>
// CHECK-DAG:       [[VAR_6_:%.+]] = "onnx.Reshape"([[VAR_1_]], [[VAR_2_]]) {allowzero = 0 : si64} : (tensor<4x1x1xf16>, tensor<4xi64>) -> tensor<1x4x1x1xf16>
// CHECK-DAG:       [[VAR_7_:%.+]] = "onnx.Transpose"([[VAR_6_]]) {perm = [0, 2, 3, 1]} : (tensor<1x4x1x1xf16>) -> tensor<1x1x1x4xf16>
// CHECK-DAG:       [[VAR_Y_:%.+]], [[VAR_Mean_:%.+]], [[VAR_InvStdDev_:%.+]] = "onnx.LayerNormalization"([[VAR_5_]], [[VAR_4_]], [[VAR_7_]]) {axis = 3 : si64, epsilon = {{.*}} : f32, stash_type = 1 : si64} : (tensor<1x8x8x4xf16>, tensor<1x1x1x4xf16>, tensor<1x1x1x4xf16>) -> (tensor<1x8x8x4xf16>, none, none)
// CHECK:           [[VAR_8_:%.+]] = "onnx.Transpose"([[VAR_Y_]]) {perm = [0, 3, 1, 2]} : (tensor<1x8x8x4xf16>) -> tensor<1x4x8x8xf16>
// CHECK:           return [[VAR_8_]] : tensor<1x4x8x8xf16>
// CHECK:         }
