//********************************************************
//   Do not modify this file directly.
//   This file is automatically generated via script.
//   Details can be found in docs/ImportONNXDefs.md .
//********************************************************

// IMPLEMENT YOUR VERIFY LOGIC HERE
// Move to: src/Dialect/ONNX/ONNXOps/Additional/XCOMPILERVerify.cpp

#include "XCOMPILERVerify.hpp"
#include "src/Dialect/ONNX/ONNXOps/OpHelper.hpp"

using namespace mlir;
using namespace onnx_mlir;

namespace mlir {

LogicalResult XCOMPILERFusedEltwiseOpVerify(Operation *op) {
  // TODO: Implement verification for FusedEltwise
  // 
  // Cast to specific op type:
  // auto customOp = dyn_cast<XCOMPILERFusedEltwiseOp>(op);
  // if (!customOp) return failure();
  // 
  // Verify operand types, shapes, attributes, etc.
  // Example: Check that input tensors have expected rank
  // if (operandType.getRank() < 2)
  //   return op->emitError("Expected input rank >= 2");
  
  return success();
}

} // namespace mlir
