//********************************************************
//   Do not modify this file directly.
//   This file is automatically generated via script.
//   Details can be found in docs/ImportONNXDefs.md .
//********************************************************

// DO NOT EDIT - Auto-generated forwarding stubs
// This file forwards to manual implementations in shape inference, verify, and
// fold files Copy this file to
// src/Dialect/ONNX/ONNXOps/Additional/XCOMPILER.cpp

#include "XCOMPILERShapeInference.hpp"
#include "XCOMPILERVerify.hpp"
#include "src/Dialect/ONNX/ONNXOps/OpHelper.hpp"

using namespace mlir;
using namespace onnx_mlir;

// ============================================================
// Shape Inference
// ============================================================

LogicalResult XCOMPILERFusedEltwiseOp::inferShapes(
    std::function<void(Region &)> doShapeInference) {
  return XCOMPILERFusedEltwiseOpShapeInference(
      this->getOperation(), doShapeInference);
}

// ============================================================
// Verify
// ============================================================

LogicalResult XCOMPILERFusedEltwiseOp::verify() {
  return XCOMPILERFusedEltwiseOpVerify(this->getOperation());
}
