//********************************************************
//   Do not modify this file directly.
//   This file is automatically generated via script.
//   Details can be found in docs/ImportONNXDefs.md .
//********************************************************

// Shape inference function declarations for XCOMPILER operations
// This file is auto-generated - DO NOT EDIT

#pragma once

#include "mlir/IR/Operation.h"
#include "llvm/ADT/FunctionExtras.h"

namespace mlir {

// Shape inference for FusedEltwise
LogicalResult XCOMPILERFusedEltwiseOpShapeInference(
    Operation *op, std::function<void(Region &)> doShapeInference);

// Shape inference for DepthwiseConv
LogicalResult XCOMPILERDepthwiseConvOpShapeInference(
    Operation *op, std::function<void(Region &)> doShapeInference);

// Shape inference for Requantize
LogicalResult XCOMPILERRequantizeOpShapeInference(
    Operation *op, std::function<void(Region &)> doShapeInference);

} // namespace mlir
