//********************************************************
//   Do not modify this file directly.
//   This file is automatically generated via script.
//   Details can be found in docs/ImportONNXDefs.md .
//********************************************************

// Verify function declarations for XCOMPILER operations
// This file is auto-generated - DO NOT EDIT

#pragma once

#include "mlir/IR/Operation.h"
#include "mlir/Support/LogicalResult.h"

namespace mlir {

// Verify for FusedEltwise
LogicalResult XCOMPILERFusedEltwiseOpVerify(Operation *op);

} // namespace mlir
