//********************************************************
//   Do not modify this file directly.
//   This file is automatically generated via script.
//   Details can be found in docs/ImportONNXDefs.md .
//********************************************************

// IMPLEMENT YOUR SHAPE INFERENCE HERE
// This file contains templates - safe to edit and customize
// Move to: src/Dialect/ONNX/ONNXOps/Additional/XCOMPILERShapeInference.cpp
// and add it to the CMakeLists.txt in src/Dialect/ONNX/

#include "XCOMPILERShapeInference.hpp"
#include "src/Dialect/ONNX/ONNXOps/OpHelper.hpp"
#include "src/Dialect/ONNX/ONNXOps/ShapeHelper.hpp"

using namespace mlir;
using namespace onnx_mlir;

namespace mlir {

LogicalResult XCOMPILERFusedEltwiseOpShapeInference(
    Operation *op, std::function<void(Region &)> doShapeInference) {
      auto eltwiseOp = dyn_cast<XCOMPILERFusedEltwiseOp>(op);
      if (!eltwiseOp)
        return failure();
    
      // Get input A (required) and B (optional)
      Value A = eltwiseOp.getA();
      Value B = eltwiseOp.getB();
    
      // Cannot infer shape if A doesn't have shape and rank
      if (!hasShapeAndRank(A))
        return success();
    
      auto aType = mlir::cast<ShapedType>(A.getType());
      ArrayRef<int64_t> aShape = aType.getShape();
      Type elementType = aType.getElementType();
    
      SmallVector<int64_t> outputShape;
    
      // Check if B is provided (not None)
      if (B && !mlir::isa<NoneType>(B.getType())) {
        // B is provided - compute broadcasted shape
        if (!hasShapeAndRank(B))
          return success();
    
        auto bType = mlir::cast<ShapedType>(B.getType());
        ArrayRef<int64_t> bShape = bType.getShape();
    
        // Compute output shape using NumPy-style broadcasting
        // Broadcasting rules:
        // - Shapes are right-aligned (compare from trailing dimensions)
        // - Dimensions are compatible if equal OR one of them is 1
        // - Output shape is maximum along each dimension
        // - Shorter shape is implicitly padded with 1s on the left
        if (!OpTrait::util::getBroadcastedShape(aShape, bShape, outputShape)) {
          return op->emitError("FusedEltwise: incompatible shapes for broadcasting")
                 << " A shape: [" << aShape << "], B shape: [" << bShape << "]";
        }
      } else {
        // B is None - output shape is same as A (unary operation)
        outputShape.assign(aShape.begin(), aShape.end());
      }
    
      auto resultType = RankedTensorType::get(outputShape, elementType);
      eltwiseOp.getResult().setType(resultType);
    
      
  return success();
}

} // namespace mlir
