//********************************************************
//   Do not modify this file directly.
//   This file is automatically generated via script.
//   Details can be found in docs/ImportONNXDefs.md .
//********************************************************

// DO NOT EDIT - Auto-generated forwarding stubs
// This file forwards to manual implementations in shape inference, verify, and
// fold files Copy this file to src/Dialect/ONNX/ONNXOps/Additional/XFE.cpp

#include "XFEShapeInference.hpp"
#include "XFEVerify.hpp"
#include "src/Dialect/ONNX/ONNXOps/OpHelper.hpp"

using namespace mlir;
using namespace onnx_mlir;

// ============================================================
// Shape Inference
// ============================================================

LogicalResult XFEMatMulBiasOp::inferShapes(
    std::function<void(Region &)> doShapeInference) {
  return XFEMatMulBiasOpShapeInference(this->getOperation(), doShapeInference);
}

LogicalResult XFEConvOp::inferShapes(
    std::function<void(Region &)> doShapeInference) {
  return XFEConvOpShapeInference(this->getOperation(), doShapeInference);
}

LogicalResult XFEConvTransposeOp::inferShapes(
    std::function<void(Region &)> doShapeInference) {
  return XFEConvTransposeOpShapeInference(
      this->getOperation(), doShapeInference);
}

LogicalResult XFEAveragePoolOp::inferShapes(
    std::function<void(Region &)> doShapeInference) {
  return XFEAveragePoolOpShapeInference(this->getOperation(), doShapeInference);
}

LogicalResult XFEMaxPoolOp::inferShapes(
    std::function<void(Region &)> doShapeInference) {
  return XFEMaxPoolOpShapeInference(this->getOperation(), doShapeInference);
}

LogicalResult XFEGlobalAveragePoolOp::inferShapes(
    std::function<void(Region &)> doShapeInference) {
  return XFEGlobalAveragePoolOpShapeInference(
      this->getOperation(), doShapeInference);
}

LogicalResult XFEGlobalMaxPoolOp::inferShapes(
    std::function<void(Region &)> doShapeInference) {
  return XFEGlobalMaxPoolOpShapeInference(
      this->getOperation(), doShapeInference);
}

LogicalResult XFEInstanceNormalizationOp::inferShapes(
    std::function<void(Region &)> doShapeInference) {
  return XFEInstanceNormalizationOpShapeInference(
      this->getOperation(), doShapeInference);
}

LogicalResult XFEDepthToSpaceOp::inferShapes(
    std::function<void(Region &)> doShapeInference) {
  return XFEDepthToSpaceOpShapeInference(
      this->getOperation(), doShapeInference);
}

LogicalResult XFESpaceToDepthOp::inferShapes(
    std::function<void(Region &)> doShapeInference) {
  return XFESpaceToDepthOpShapeInference(
      this->getOperation(), doShapeInference);
}

LogicalResult XFEResizeOp::inferShapes(
    std::function<void(Region &)> doShapeInference) {
  return XFEResizeOpShapeInference(this->getOperation(), doShapeInference);
}

// ============================================================
// Verify
// ============================================================

LogicalResult XFEMatMulBiasOp::verify() {
  if (failed(XFEMatMulBiasOpVerify(this->getOperation())))
    return failure();
  return XFEChannelWiseQuantizationVerify(this->getOperation());
}

LogicalResult XFEConvOp::verify() {
  if (failed(XFEConvOpVerify(this->getOperation())))
    return failure();
  return XFEChannelWiseQuantizationVerify(this->getOperation());
}

LogicalResult XFEConvTransposeOp::verify() {
  if (failed(XFEConvTransposeOpVerify(this->getOperation())))
    return failure();
  return XFEChannelWiseQuantizationVerify(this->getOperation());
}

LogicalResult XFEAveragePoolOp::verify() {
  if (failed(XFEAveragePoolOpVerify(this->getOperation())))
    return failure();
  return XFEChannelWiseQuantizationVerify(this->getOperation());
}

LogicalResult XFEMaxPoolOp::verify() {
  if (failed(XFEMaxPoolOpVerify(this->getOperation())))
    return failure();
  return XFEChannelWiseQuantizationVerify(this->getOperation());
}

LogicalResult XFEGlobalAveragePoolOp::verify() {
  if (failed(XFEGlobalAveragePoolOpVerify(this->getOperation())))
    return failure();
  return XFEChannelWiseQuantizationVerify(this->getOperation());
}

LogicalResult XFEGlobalMaxPoolOp::verify() {
  if (failed(XFEGlobalMaxPoolOpVerify(this->getOperation())))
    return failure();
  return XFEChannelWiseQuantizationVerify(this->getOperation());
}

LogicalResult XFEInstanceNormalizationOp::verify() {
  if (failed(XFEInstanceNormalizationOpVerify(this->getOperation())))
    return failure();
  return XFEChannelWiseQuantizationVerify(this->getOperation());
}

LogicalResult XFEDepthToSpaceOp::verify() {
  if (failed(XFEDepthToSpaceOpVerify(this->getOperation())))
    return failure();
  return XFEChannelWiseQuantizationVerify(this->getOperation());
}

LogicalResult XFESpaceToDepthOp::verify() {
  if (failed(XFESpaceToDepthOpVerify(this->getOperation())))
    return failure();
  return XFEChannelWiseQuantizationVerify(this->getOperation());
}

LogicalResult XFEResizeOp::verify() {
  if (failed(XFEResizeOpVerify(this->getOperation())))
    return failure();
  return XFEChannelWiseQuantizationVerify(this->getOperation());
}
