//********************************************************
//   Do not modify this file directly.
//   This file is automatically generated via script.
//   Details can be found in docs/ImportONNXDefs.md .
//********************************************************

// Shape inference function declarations for XFE operations
// This file is auto-generated - DO NOT EDIT

#pragma once

#include "mlir/IR/Operation.h"
#include "llvm/ADT/FunctionExtras.h"

namespace mlir {

// Shape inference for MatMulBias
LogicalResult XFEMatMulBiasOpShapeInference(
    Operation *op, std::function<void(Region &)> doShapeInference);

// Shape inference for ConvChannelLast
LogicalResult XFEConvOpShapeInference(
    Operation *op, std::function<void(Region &)> doShapeInference);

// Shape inference for ConvTransposeChannelLast
LogicalResult XFEConvTransposeOpShapeInference(
    Operation *op, std::function<void(Region &)> doShapeInference);

// Shape inference for AveragePoolChannelLast
LogicalResult XFEAveragePoolOpShapeInference(
    Operation *op, std::function<void(Region &)> doShapeInference);

// Shape inference for MaxPoolChannelLast
LogicalResult XFEMaxPoolOpShapeInference(
    Operation *op, std::function<void(Region &)> doShapeInference);

// Shape inference for GlobalAveragePoolChannelLast
LogicalResult XFEGlobalAveragePoolOpShapeInference(
    Operation *op, std::function<void(Region &)> doShapeInference);

// Shape inference for GlobalMaxPoolChannelLast
LogicalResult XFEGlobalMaxPoolOpShapeInference(
    Operation *op, std::function<void(Region &)> doShapeInference);

// Shape inference for InstanceNormalizationChannelLast
LogicalResult XFEInstanceNormalizationOpShapeInference(
    Operation *op, std::function<void(Region &)> doShapeInference);

// Shape inference for DepthToSpaceChannelLast
LogicalResult XFEDepthToSpaceOpShapeInference(
    Operation *op, std::function<void(Region &)> doShapeInference);

// Shape inference for SpaceToDepthChannelLast
LogicalResult XFESpaceToDepthOpShapeInference(
    Operation *op, std::function<void(Region &)> doShapeInference);

// Shape inference for ResizeChannelLast
LogicalResult XFEResizeOpShapeInference(
    Operation *op, std::function<void(Region &)> doShapeInference);

} // namespace mlir
