//********************************************************
//   Do not modify this file directly.
//   This file is automatically generated via script.
//   Details can be found in docs/ImportONNXDefs.md .
//********************************************************

// Shape inference function declarations for XFE operations
// This file is auto-generated - DO NOT EDIT

#pragma once

#include "mlir/IR/Operation.h"
#include "llvm/ADT/FunctionExtras.h"

namespace mlir {

// Shape inference for MatMulBias
LogicalResult XFEMatMulBiasOpShapeInference(
    Operation *op, std::function<void(Region &)> doShapeInference);

// Shape inference for Conv
LogicalResult XFEConvOpShapeInference(
    Operation *op, std::function<void(Region &)> doShapeInference);

// Shape inference for ConvTranspose
LogicalResult XFEConvTransposeOpShapeInference(
    Operation *op, std::function<void(Region &)> doShapeInference);

// Shape inference for AveragePool
LogicalResult XFEAveragePoolOpShapeInference(
    Operation *op, std::function<void(Region &)> doShapeInference);

// Shape inference for MaxPool
LogicalResult XFEMaxPoolOpShapeInference(
    Operation *op, std::function<void(Region &)> doShapeInference);

// Shape inference for GlobalAveragePool
LogicalResult XFEGlobalAveragePoolOpShapeInference(
    Operation *op, std::function<void(Region &)> doShapeInference);

// Shape inference for GlobalMaxPool
LogicalResult XFEGlobalMaxPoolOpShapeInference(
    Operation *op, std::function<void(Region &)> doShapeInference);

// Shape inference for BatchNormalization
LogicalResult XFEBatchNormalizationOpShapeInference(
    Operation *op, std::function<void(Region &)> doShapeInference);

// Shape inference for InstanceNormalization
LogicalResult XFEInstanceNormalizationOpShapeInference(
    Operation *op, std::function<void(Region &)> doShapeInference);

// Shape inference for DepthToSpace
LogicalResult XFEDepthToSpaceOpShapeInference(
    Operation *op, std::function<void(Region &)> doShapeInference);

// Shape inference for SpaceToDepth
LogicalResult XFESpaceToDepthOpShapeInference(
    Operation *op, std::function<void(Region &)> doShapeInference);

// Shape inference for GroupNormalization
LogicalResult XFEGroupNormalizationOpShapeInference(
    Operation *op, std::function<void(Region &)> doShapeInference);

// Shape inference for Resize
LogicalResult XFEResizeOpShapeInference(
    Operation *op, std::function<void(Region &)> doShapeInference);

// Shape inference for GridSample
LogicalResult XFEGridSampleOpShapeInference(
    Operation *op, std::function<void(Region &)> doShapeInference);

} // namespace mlir
