//********************************************************
//   Do not modify this file directly.
//   This file is automatically generated via script.
//   Details can be found in docs/ImportONNXDefs.md .
//********************************************************

// Verify function declarations for XFE operations
// This file is auto-generated - DO NOT EDIT

#pragma once

#include "mlir/IR/Operation.h"
#include "mlir/Support/LogicalResult.h"

namespace mlir {

// Verify for MatMulBias
LogicalResult XFEMatMulBiasOpVerify(Operation *op);

// Verify for Conv
LogicalResult XFEConvOpVerify(Operation *op);

// Verify for ConvTranspose
LogicalResult XFEConvTransposeOpVerify(Operation *op);

// Verify for AveragePool
LogicalResult XFEAveragePoolOpVerify(Operation *op);

// Verify for MaxPool
LogicalResult XFEMaxPoolOpVerify(Operation *op);

// Verify for GlobalAveragePool
LogicalResult XFEGlobalAveragePoolOpVerify(Operation *op);

// Verify for GlobalMaxPool
LogicalResult XFEGlobalMaxPoolOpVerify(Operation *op);

// Verify for BatchNormalization
LogicalResult XFEBatchNormalizationOpVerify(Operation *op);

// Verify for InstanceNormalization
LogicalResult XFEInstanceNormalizationOpVerify(Operation *op);

// Verify for DepthToSpace
LogicalResult XFEDepthToSpaceOpVerify(Operation *op);

// Verify for SpaceToDepth
LogicalResult XFESpaceToDepthOpVerify(Operation *op);

// Verify for Resize
LogicalResult XFEResizeOpVerify(Operation *op);

} // namespace mlir
