//********************************************************
//   Do not modify this file directly.
//   This file is automatically generated via script.
//   Details can be found in docs/ImportONNXDefs.md .
//********************************************************

// Verify function declarations for XFE operations
// This file is auto-generated - DO NOT EDIT

#pragma once

#include "mlir/IR/Operation.h"
#include "mlir/Support/LogicalResult.h"

namespace mlir {

// Verify for MatMulBias
LogicalResult XFEMatMulBiasOpVerify(Operation *op);

// Verify for ConvChannelLast
LogicalResult XFEConvOpVerify(Operation *op);

// Verify for AveragePoolChannelLast
LogicalResult XFEAveragePoolOpVerify(Operation *op);

// Verify for MaxPoolChannelLast
LogicalResult XFEMaxPoolOpVerify(Operation *op);

// Verify for GlobalAveragePoolChannelLast
LogicalResult XFEGlobalAveragePoolOpVerify(Operation *op);

// Verify for GlobalMaxPoolChannelLast
LogicalResult XFEGlobalMaxPoolOpVerify(Operation *op);

// Verify for InstanceNormalizationChannelLast
LogicalResult XFEInstanceNormalizationOpVerify(Operation *op);

// Verify for DepthToSpaceChannelLast
LogicalResult XFEDepthToSpaceOpVerify(Operation *op);

// Verify for SpaceToDepthChannelLast
LogicalResult XFESpaceToDepthOpVerify(Operation *op);

} // namespace mlir
