/*
 * SPDX-License-Identifier: Apache-2.0
 */

//===------- InstrumentCleanupPass.cpp - Instrumentation -----------------===//
//
// Copyright 2025 The IBM Research Authors.
//
// =============================================================================
//
// This file implements a Function level pass that remove consecutive
// instrumentation operations (first with "before" tag and second with "after")
// as they do not measure anything.
//
//===----------------------------------------------------------------------===//

#include <regex>
#include <set>
#include <string>

#include "onnx-mlir/Compiler/OMCompilerRuntimeTypes.h"
#include "onnx-mlir/Compiler/OMCompilerTypes.h"

#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/Interfaces/CallInterfaces.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/Passes.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/Support/raw_ostream.h"

#include "src/Compiler/OptionUtils.hpp"
#include "src/Dialect/Krnl/KrnlOps.hpp"
#include "src/Interface/ShapeInferenceOpInterface.hpp"
#include "src/Pass/Passes.hpp"
#include "llvm/Support/Debug.h"

// It may be useful to list the empty instrumentation, as it may indicate
// operations that were wrongfully removed.
#define DEBUG_TYPE "print-empty-instrumentation"

using namespace mlir;

namespace onnx_mlir {

#define GEN_PASS_DEF_INSTRUMENTCLEANUPPASS
#include "src/Transform/Passes.h.inc"

/*!
 * This pass insert KrnlInstrumentOp before and after each ops
 */

class InstrumentCleanupPass
    : public impl::InstrumentCleanupPassBase<InstrumentCleanupPass> {
public:
  MLIR_DEFINE_EXPLICIT_INTERNAL_INLINE_TYPE_ID(InstrumentCleanupPass)

  void runOnOperation() override {
    llvm::SmallVector<Operation *> eraseOpList, debugOpList;
    // Number of consecutive ops that were removed and that we should skip.
    int skipNext = 0;

    // Iterate on the operations nested in this function
    getOperation().walk([&](mlir::Operation *op) -> WalkResult {
      if (skipNext > 0) {
        skipNext--;
        return WalkResult::advance();
      }
      KrnlInstrumentOp firstInstrOp = mlir::dyn_cast<KrnlInstrumentOp>(op);
      // Check if we have a first instrumentation op with instr before.
      if (!firstInstrOp)
        return WalkResult::advance();
      uint64_t firstTag = firstInstrOp.getTag();
      // skip if not before, or if this call initializes the instrumentation.
      if (!IS_INSTRUMENT_BEFORE_OP(firstTag) || IS_INSTRUMENT_INIT(firstTag))
        return WalkResult::advance();
      // Check if we have a second instrumentation op with instr after.
      Operation *nextOp = op->getNextNode();
      if (!nextOp)
        return WalkResult::advance();
      KrnlInstrumentOp secondInstrOp = mlir::dyn_cast<KrnlInstrumentOp>(nextOp);
      if (!secondInstrOp)
        return WalkResult::advance();
      uint64_t secondTag = secondInstrOp.getTag();
      // skip if not after, or if this call initializes the instrumentation.
      if (!IS_INSTRUMENT_AFTER_OP(secondTag) || IS_INSTRUMENT_INIT(secondTag))
        return WalkResult::advance();
      // Could check opName but we already have a before/after pair, it can only
      // be of the same op.
      // Schedule both instrumentation to be removed as there is nothing between
      // the start and the stop of the instrumentation.
      eraseOpList.emplace_back(op);
      eraseOpList.emplace_back(nextOp);
      skipNext = 1;
      LLVM_DEBUG({
        std::string opName = firstInstrOp.getOpName().str();
        std::string constSubstring = "Const";
        if (opName.find(constSubstring) == std::string::npos)
          debugOpList.emplace_back(op);
      });
      // Remove all subsequent Print Tensor as they are generated by printing
      // the signature of the removed op.
      while (true) {
        nextOp = nextOp->getNextNode();
        if (!nextOp || !mlir::dyn_cast<KrnlPrintTensorOp>(nextOp))
          break;
        eraseOpList.emplace_back(nextOp);
        skipNext++;
      }
      return WalkResult::advance();
    });
    LLVM_DEBUG({
      llvm::dbgs() << "List of empty instrumentations: start\n";
      for (Operation *op : debugOpList) {
        op->dump();
      }
      llvm::dbgs() << "List of empty instrumentations: end\n";
    });
    // Remove ops.
    for (Operation *op : eraseOpList)
      op->erase();
  }
};
} // namespace onnx_mlir
