#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0

####################### IsolatePass.py #########################################
#
# Copyright 2025-2026 The IBM Research Authors.
#
################################################################################
#
# This script is used to identify a specific pass from a file listing several
# passes, e.g. when using onnx-mlir -mlir-print-after-all
#
################################################################################

import argparse
import os
import re

from mlir_log_utils import clean_line, apply_comments, apply_wrap

# Global variables.

# Id is the entry number in the array. Each entry contains a string with all of
# #the code associated with that pass
pass_listing = []
# Map the name to the id that has it. Value is a list a pass can be called several times.
pass_name_to_id = {}
# Map the id to the pass name that represented it.
id_to_pass_name = []
debug = 0


def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "input_pos",
        nargs="?",
        help="Same as -i/--input, provided as a positional argument.",
        metavar="NAME",
    )
    parser.add_argument(
        "-i",
        "--input",
        help="Provide the NAME input log file to parse, e.g. a file "
        "generated by an 'onnx-mlir --mlir-print-after-all' command.",
        metavar="NAME",
    )
    parser.add_argument(
        "-p",
        "--pass-name",
        help="Name of the pass to list. When regexp matches "
        "multiple passes, use -n option to indicate which match to select.",
        metavar="REGEX",
    )
    parser.add_argument(
        "-n",
        "--num",
        help="Id NUM of the pass to list when -p is not specified. "
        "Otherwise, list the NUM(th) match returned by the -p regex string.",
        metavar="NUM",
    )
    parser.add_argument(
        "-a",
        "--after",
        help="If STR is a number, N, print the pass Nth after the pass indicated by the  "
        "-p or -n options. Number N can be negative. Otherwise, print the next pass that "
        "matches the regex STR.",
        metavar="STR",
    )
    parser.add_argument(
        "-l",
        "--list-passes",
        action="store_true",
        help="List the name of every passes. Default on when missing the -p or -n options.",
    )
    parser.add_argument(
        "-c",
        "--comments",
        action="store_true",
        help="Add useful comments to the printed listing: use-count for each def; values for scalar constant.",
    )
    parser.add_argument(
        "-w",
        "--wrap",
        action="store_true",
        help="Reformat long func signatures / ops / returns across multiple indented "
        "lines when they exceed the line-length limit (same transform as AnalyzeShape.py).",
    )
    return parser.parse_args()


def usage(error_message):
    print("Error:", error_message)
    print("Use -h / --help for more information.")
    exit(1)


###########################################################
# Scan listing

# Fill pass_name_to_id, id_to_pass_name, pass_listing


def extract_ir_pass_name(text):
    pattern = r"// -----// IR Dump After(.*?) //----- //"
    match = re.search(pattern, text)
    if match:
        return match.group(1).strip()
    else:
        return None


def process_line(str):
    if str.endswith("\n"):
        str = str[:-1]
    return clean_line(str) + "\n"


def scan_listing(filename, print_list_name):
    global pass_name_to_id, id_to_pass_name, pass_listing
    pass_name_to_id = {}
    id_to_pass_name = []
    pass_listing = []

    current_listing = []
    current_name = ""
    try:
        with open(filename, "r") as file:
            for line in file:
                if re.match(r"^onnx-mlir ", line):
                    print(f"// Command:\n// {line}\n")
                    continue
                pass_name = extract_ir_pass_name(line)
                if pass_name:
                    if current_name:
                        if current_listing:
                            # Save current listing.
                            id = len(pass_listing)
                            pass_listing.append("".join(current_listing))
                            id_to_pass_name.append(current_name)
                            if current_name in pass_name_to_id:
                                pass_name_to_id[current_name].append(id)
                            else:
                                pass_name_to_id[current_name] = [id]
                            # Print info if requested.
                            if print_list_name:
                                print(f"{id}: {current_name}")
                    # Save new current name
                    current_name = pass_name
                    current_listing = []
                current_listing.append(process_line(line))
            # Flush the last pass listing (no subsequent header to trigger it).
            if current_name and current_listing:
                id = len(pass_listing)
                pass_listing.append("".join(current_listing))
                id_to_pass_name.append(current_name)
                if current_name in pass_name_to_id:
                    pass_name_to_id[current_name].append(id)
                else:
                    pass_name_to_id[current_name] = [id]
                if print_list_name:
                    print(f"{id}: {current_name}")
            elif not pass_listing and current_listing:
                # No IR Dump After header was ever found in the file. Treat
                # the whole content as a single unnamed pass so that "-n 0"
                # (with no -p) still works on plain, headerless MLIR files.
                id = len(pass_listing)
                pass_listing.append("".join(current_listing))
                id_to_pass_name.append("")
                if print_list_name:
                    print(f"{id}: (no pass header found)")
    except FileNotFoundError:
        print(f"Error: The file '{filename}' was not found.")
        raise
    except IOError as e:
        print(f"Error: Could not read file '{filename}'. Reason: {e}")
        raise


###########################################################
# Locate the pass, namely return the id associated with what we are
# looking for. Id will point to a string in pass_listing.


def locate_pass(name, num):
    global pass_name_to_id, pass_listing

    ids = []
    regex = re.compile(name)
    for key in pass_name_to_id:
        if regex.search(key):
            curr_ids = pass_name_to_id[key]
            ids.extend(curr_ids)
            if debug:
                print(f" Matched key: {key} -> Value: {id}")
    num_ids = len(ids)
    if num_ids == 0:
        usage(
            f"pass {name} not found; please check the name of the pass you are looking for."
        )
    if num_ids > 1:
        if num:
            n = int(num)
            if n < 0 or n >= num_ids:
                usage(
                    f"Provided a -n {n} number that is not in the range [0..{num_ids})."
                )
            return ids[n]
        print(f"Pass {name} is ambiguous and matched with the following ids:")
        print("  ", ids)
        print(
            "  Please choose which one with the -n <id> option to select a unique pass."
        )
        exit(1)
    return ids[0]


###########################################################
# Print the pass that the user is interested in.


def print_pass(filename, id, after, pass_name=None):
    global pass_name_to_id, id_to_pass_name, pass_listing

    # We may want to print a pass after the one pointed by id.
    n = 0
    if after:
        if re.fullmatch(r"[+-]?\d+", after) is not None:
            # After is a number.
            n = int(after)
        else:
            # After is a pass name, locate it.
            regex = re.compile(after)
            n = 1
            while True:
                if id + n >= len(id_to_pass_name):
                    usage(f"Did not find pass {after} after pass {pass_name}")
                if regex.search(id_to_pass_name[id + n]):
                    # Found it
                    break
                n += 1
        id += n
    if id < 0 or id >= len(pass_listing):
        print(f"Out of bound id {id}, should be in [0..{len(pass_listing)}) range.")
        exit(1)
    # Expand to the full block of consecutive same-named passes so that
    # function-level passes (which emit one header per function) are shown
    # together rather than in isolation.
    target_name = id_to_pass_name[id]
    start_id = id
    while start_id > 0 and id_to_pass_name[start_id - 1] == target_name:
        start_id -= 1
    end_id = id
    while end_id + 1 < len(pass_listing) and id_to_pass_name[end_id + 1] == target_name:
        end_id += 1
    id_range = f"{start_id}" if start_id == end_id else f"{start_id}..{end_id}"
    message = f"// Printing pass with id {id_range}"
    if pass_name:
        if n != 0:
            if n > 0:
                message += f", {n}(th) pass(s) after {pass_name}"
            else:
                message += f", {-n}(th) pass(s) before {pass_name}"
        else:
            message += f" with name {pass_name}"
    message += f' from file "{filename}".'
    # Actual printing
    mlir_text = "".join(pass_listing[i] for i in range(start_id, end_id + 1))
    # -w must run before -c: -c appends "/N" and "=value" suffixes onto SSA
    # names, which then fail the head regexes -w's dispatchers use to
    # recognize generic ops / returns, silently skipping their wrap.
    if args.wrap:
        mlir_text = apply_wrap(mlir_text)
    if args.comments:
        mlir_text = apply_comments(mlir_text)
    print(f"{message}\n\n", mlir_text, f"\n\n{message}")


# Process arguments
args = get_args()
if args.input == None:
    args.input = args.input_pos
if args.input == None:
    usage("missing file name")
if args.pass_name == None and args.num == None:
    args.list_passes = True

# Perform hte listing.
scan_listing(args.input, args.list_passes)
if args.list_passes:
    exit(0)
if args.pass_name:
    id = locate_pass(args.pass_name, args.num)
    print_pass(args.input, id, args.after, args.pass_name)
elif args.num:
    print_pass(args.input, int(args.num), args.after)
