#!/usr/bin/env python3
"""
v2 driver — the inference workload .cpp (main(), the invoke_run wrapper,
argv parsing, the timing loop) is embedded in this script as a string
constant. The user only writes one function:

    extern "C" OMTensorList *initialize_model_input(void);

It is called ONCE before the timing loop starts and the returned tensor
list is reused for every invoke_run iteration. Buffer lifetime is the
function's responsibility — typically `static` arrays inside the function.

Everything else (per-binary leaf samples, per-frame attribution,
instruction-mix histogram, per-ONNX-op breakdown via OMInstrumentPoint
markers) is identical to v1.

How "inside the model" is detected
----------------------------------
The embedded workload defines a small `invoke_run()` wrapper around
`run_main_graph` and is built with `-g` so the symbol is visible in
`sample` output. A stack is "inside the model" iff `invoke_run` appears
anywhere as an ancestor frame.

Pipeline
--------
  1. Compile the embedded workload .cpp + the user's init .cpp +
     model.so into a single static binary (clang++, -O2 -g, linking
     the model.so directly so dyld will load it at process start).
  2. Spawn the binary with `-t <duration+10>` so the workload outlasts
     the sampling window. DYLD_LIBRARY_PATH points at the .so's
     directory in case its install_name is just a basename.
  3. Run macOS `sample <pid> <duration> -f <out>`.
  4. Walk the call graph: total samples, inside-marker samples,
     per-binary leaves, top frames.
  5. Disassemble model.so and produce the instruction-mix histogram
     (and, if the .so was built with --profile-ir, the per-ONNX-op
     attribution via OMInstrumentPoint markers).
  6. Write a JSON profile and print the summary.

"""

import argparse
import datetime
import json
import os
import re
import subprocess
import sys
import time
from collections import namedtuple

PROFILE_FORMAT_VERSION = 3
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# Platform dispatch. The macOS path uses Apple's `sample` tool +
# `otool`-style Mach-O introspection; the Linux path uses `perf record`
# + `readelf`/`/proc/<pid>/maps` for the equivalents. Everything between
# (extractors, dataflow, reports, JSON I/O) is platform-agnostic.
IS_MAC = sys.platform == 'darwin'
IS_LINUX = sys.platform.startswith('linux')
if not (IS_MAC or IS_LINUX):
    sys.exit(f"Error: unsupported platform {sys.platform!r}; "
             "only macOS (darwin) and Linux are wired up.")

# Env var the loader reads to find dependent .so/.dylib files.
DYLIB_PATH_ENV = 'DYLD_LIBRARY_PATH' if IS_MAC else 'LD_LIBRARY_PATH'


def _so_arch(so_path):
    """Return 'arm64', 'x86_64', or 'unknown' for the .so's machine type.

    Used to gate the per-ONNX-op OMInstrumentPoint dataflow recovery —
    the adrp+add+mov chain it walks is arm64-specific. x86_64 would
    need a separate implementation (RIP-relative LEA + reg moves), so
    we silently skip it for now.
    """
    r = subprocess.run(['file', so_path], capture_output=True, text=True)
    out = (r.stdout or '').lower()
    if 'aarch64' in out or 'arm64' in out:
        return 'arm64'
    if 'x86-64' in out or 'x86_64' in out:
        return 'x86_64'
    return 'unknown'

# A row of the macOS `sample` Call graph section, post-parse. `depth` is
# the unified tree depth (indent + 1 if the line was a '+' continuation
# of its parent). `pcs` is the list of integer PCs from the bracketed
# trailer; leader lines have one PC, '+' lines have a comma list.
Frame = namedtuple('Frame', ['depth', 'count', 'symbol', 'binary', 'pcs'])

# The marker frame the workload wraps run_main_graph in. Any stack that
# passes through this symbol is counted as "inside the model".
INSIDE_MARKER = "invoke_run"

# Embedded inference-workload .cpp. The user supplies a separate .cpp
# defining `extern "C" OMTensorList *initialize_model_input(void);`;
# this file provides everything else (main, argv parsing, the noinline
# invoke_run wrapper that survives tail-call optimization, the timing
# loop). The driver writes this string to a temp file and compiles it
# alongside the user's init .cpp.
WORKLOAD_CPP = r'''// Auto-generated by profile-model.py.
// The user's companion .cpp must define:
//   extern "C" OMTensorList *initialize_model_input(void);

#include <chrono>
#include <cstdint>
#include <cstdlib>
#include <iostream>
#include <string>

#include <OnnxMlirRuntime.h>

extern "C" OMTensorList *run_main_graph(OMTensorList *);
extern "C" OMTensorList *initialize_model_input(void);

// Thin wrapper around run_main_graph. Same purpose as the v1 .cpp:
// give every model invocation one easy-to-grep frame so the python
// driver can identify "inside the model" stacks. noinline alone is not
// enough because clang -O2 will tail-call-optimize the bare
// `return run_main_graph(input)` into a direct jump, dropping the
// frame; the asm volatile barrier forces `r` to live past the call,
// which disables TCO and keeps the frame on the stack.
extern "C" __attribute__((noinline)) OMTensorList *
invoke_run(OMTensorList *input) {
  OMTensorList *r = run_main_graph(input);
  asm volatile("" : : "r"(r) : "memory");
  return r;
}

int main(int argc, char *argv[]) {
  // Tiny hand-rolled flag parser. Accepted forms:
  //   (no args)
  //   -t 30
  //   --time 30
  int duration = 40;
  for (int i = 1; i < argc; ++i) {
    const std::string a = argv[i];
    if ((a == "-t" || a == "--time") && i + 1 < argc) {
      duration = std::atoi(argv[++i]);
    } else {
      std::cerr << "Usage: " << argv[0] << " [-t|--time <seconds>]\n";
      return 1;
    }
  }
  if (duration <= 0) {
    std::cerr << "Usage: " << argv[0] << " [-t|--time <seconds>]\n";
    return 1;
  }

  OMTensorList *input = initialize_model_input();
  if (!input) {
    std::cerr << "initialize_model_input() returned null\n";
    return 2;
  }

  const auto start = std::chrono::steady_clock::now();
  int iteration = 0;

  while (true) {
    const auto now = std::chrono::steady_clock::now();
    const double elapsed = std::chrono::duration<double>(now - start).count();
    if (elapsed >= duration)
      break;

    OMTensorList *outputList = invoke_run(input);
    if (!outputList) {
      std::cerr << "invoke_run returned null\n";
      omTensorListDestroy(input);
      return 5;
    }

    ++iteration;
    if (iteration % 50 == 0) {
      std::cout << "Iteration " << iteration << "  (" << elapsed << "s / "
                << duration << "s)" << std::endl;
    }

    omTensorListDestroy(outputList);
  }

  omTensorListDestroy(input);

  const double total =
      std::chrono::duration<double>(std::chrono::steady_clock::now() - start)
          .count();
  std::cout << "Completed " << iteration << " iterations in " << total << "s"
            << std::endl;
  return 0;
}
'''

# Where to write the workload .cpp + the binary it builds. /tmp keeps
# both out of the user's source tree and avoids surprise file creation
# next to their init .cpp.
WORKLOAD_CPP_PATH = "/tmp/profile-static-workload-v2.cpp"
DEFAULT_BINARY_PATH = "/tmp/profile-cpp-model-static-v2"

# Sample init .cpp printed by `--help init`. This mirrors the granite
# example shipped alongside the script — keep them in sync if the input
# shape conventions ever change. The point is to give the user a
# copy-paste-and-edit starting point: change shape/dtype/values to
# match their model's input contract; the function signature must stay
# `extern "C" OMTensorList *initialize_model_input(void)`.
SAMPLE_INIT_CPP = r'''// Example initialize_model_input() — adapt the shapes, dtypes, and
// content to your own model. The driver calls this once before the
// timing loop and reuses the returned OMTensorList* for every
// iteration. The buffers must outlive the entire process; `static`
// arrays inside the function body are the simplest way to guarantee
// that without an owning wrapper around OMTensor (omTensorCreate
// borrows the pointer; it does not copy).
//
// This particular example is for granite-embedding-278m-multilingual,
// shape-info 0:1x180,1:1x180:
//   input_ids       int64[1,180]  random in [0, 30000)
//   attention_mask  int64[1,180]  all ones

#include <cstdint>
#include <random>

#include <OnnxMlirRuntime.h>

extern "C" OMTensorList *initialize_model_input(void) {
  constexpr int64_t kBatch = 1;
  constexpr int64_t kSeqLen = 180;
  constexpr int64_t kRank = 2;
  constexpr int64_t kNumElems = kBatch * kSeqLen;

  static int64_t shape[2] = {kBatch, kSeqLen};
  static int64_t inputIds[kNumElems];
  static int64_t attentionMask[kNumElems];

  // Fixed seed → bit-identical repeat runs. The profiler doesn't care
  // about the values, only the shape of the workload.
  std::mt19937_64 rng(12345);
  std::uniform_int_distribution<int64_t> vocab(0, 29999);
  for (int64_t i = 0; i < kNumElems; ++i) {
    inputIds[i] = vocab(rng);
    attentionMask[i] = 1;
  }

  OMTensor *idsT =
      omTensorCreate(inputIds, shape, kRank, ONNX_TYPE_INT64);
  OMTensor *maskT =
      omTensorCreate(attentionMask, shape, kRank, ONNX_TYPE_INT64);
  OMTensor *list[2] = {idsT, maskT};
  return omTensorListCreate(list, 2);
}
'''

# OnnxMlirRuntime.h lives at <repo>/include/OnnxMlirRuntime.h and this
# script ships at <repo>/utils/<name>.py — derive the include directory
# rather than hard-coding so a moved checkout still builds.
DEFAULT_INCLUDE_DIR = os.path.normpath(os.path.join(SCRIPT_DIR, '..', 'include'))


def compile_workload(init_cpp, model_so, verbose=False, extra_cflags=None):
    """Compile the embedded workload + the user's init .cpp + model.so
    into a single static binary. Returns the binary path.

    Compile command (rebuilt from defaults each call):
      clang++ -std=c++17 -O2 -g -I <include-dir>
              <workload.cpp> <init.cpp> <model.so>
              -o <binary>
    Extra clang flags can be appended via `extra_cflags` (a list).
    """
    # Materialize the embedded workload .cpp to disk so clang can ingest
    # it. Overwrite each run so any edits to this script's WORKLOAD_CPP
    # take effect on the next build.
    with open(WORKLOAD_CPP_PATH, "w") as f:
        f.write(WORKLOAD_CPP)

    so_abs = os.path.abspath(model_so)
    so_dir = os.path.dirname(so_abs)
    cmd = [
        "clang++", "-std=c++17", "-O2", "-g",
        "-I", DEFAULT_INCLUDE_DIR,
        WORKLOAD_CPP_PATH,
        os.path.abspath(init_cpp),
        so_abs,
    ]
    if IS_LINUX:
        # On Linux, the ELF linker by default records the .so filename
        # (its DT_NEEDED) without any path. Embed an rpath pointing at
        # the .so's directory so dyld/ld.so finds it at process start
        # without the user having to pre-set LD_LIBRARY_PATH. We still
        # set LD_LIBRARY_PATH at run time as a belt-and-suspenders.
        cmd += ["-L", so_dir, "-Wl,-rpath," + so_dir]
    cmd += ["-o", DEFAULT_BINARY_PATH]
    if extra_cflags:
        cmd[1:1] = list(extra_cflags)  # insert just after clang++

    print(f"Compiling: workload + {init_cpp}")
    if verbose:
        print(f"  $ {' '.join(cmd)}")
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        print("--- compile stdout ---")
        print(r.stdout)
        print("--- compile stderr ---")
        print(r.stderr)
        sys.exit(f"Compile failed (exit {r.returncode}).")
    if verbose and r.stderr:
        print(r.stderr)
    if not os.path.exists(DEFAULT_BINARY_PATH):
        sys.exit(f"Compile succeeded but binary not found: "
                 f"{DEFAULT_BINARY_PATH}")
    print(f"Built: {DEFAULT_BINARY_PATH}")
    return DEFAULT_BINARY_PATH


SAMPLE_FILE_PATH = "/tmp/profile_cpp_sample.txt"
LINUX_PERF_DATA_PATH = "/tmp/profile_cpp_perf.data"
LINUX_MAPS_PATH = SAMPLE_FILE_PATH + ".maps"
WORKLOAD_STDOUT_LOG = "/tmp/profile_cpp_stdout.log"
WORKLOAD_STDERR_LOG = "/tmp/profile_cpp_stderr.log"


def _spawn_workload(binary, model_so, duration):
    """Launch the workload binary, return (proc, stdout_f, stderr_f)
    or (None, None, None) if it exited before sampling started.

    Pads the workload's `-t` by 10 s so the loop is still running when
    the sampler finishes; otherwise the last sampled second can land
    after exit and miss frames.

    Models compiled with --instrument-onnx-ops emit a per-op SIG-REPORT
    line on every inference call; for a 30 s loop that's millions of
    writes blocking the workload on stdout I/O instead of the math we're
    trying to profile. ONNX_MLIR_NO_INSTRUMENT=1 silences it at runtime
    without recompiling.

    A statically-linked model.so may have an install_name / SONAME
    that's just the basename; dyld/ld.so won't find it unless the
    directory is on the loader's search path. Prepend onto whichever
    env var the loader uses (DYLD_LIBRARY_PATH / LD_LIBRARY_PATH) so
    the user's existing value still wins for everything else.
    """
    cmd = [binary, "-t", str(duration + 10)]
    out_f = open(WORKLOAD_STDOUT_LOG, "w")
    err_f = open(WORKLOAD_STDERR_LOG, "w")
    env = os.environ.copy()
    env["ONNX_MLIR_NO_INSTRUMENT"] = "1"
    so_dir = os.path.dirname(os.path.abspath(model_so))
    existing = env.get(DYLIB_PATH_ENV, "")
    env[DYLIB_PATH_ENV] = (
        so_dir + (":" + existing if existing else ""))
    print(f"Launching: {' '.join(cmd)}")
    print("  env: ONNX_MLIR_NO_INSTRUMENT=1")
    print(f"  env: {DYLIB_PATH_ENV}={env[DYLIB_PATH_ENV]}")
    proc = subprocess.Popen(cmd, stdout=out_f, stderr=err_f, env=env)
    print(f"PID: {proc.pid}")

    # Give the process a moment to start (loader resolves model.so,
    # init buffers) so sampling starts mid-loop rather than during init.
    time.sleep(2)
    if proc.poll() is not None:
        out_f.close()
        err_f.close()
        print("Workload exited immediately:")
        for label, p in (("stdout", WORKLOAD_STDOUT_LOG),
                         ("stderr", WORKLOAD_STDERR_LOG)):
            try:
                with open(p) as f:
                    tail = f.read()[-4000:]
                if tail:
                    print(f"--- {label} (tail) ---")
                    print(tail)
            except OSError:
                pass
        return None, None, None
    return proc, out_f, err_f


def _wait_workload(proc, out_f, err_f):
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        proc.terminate()
        proc.wait()
    out_f.close()
    err_f.close()


def run_and_sample(binary, model_so, duration):
    """Spawn the binary, sample its PID for `duration` seconds, return
    the path to the parsed sampler-output file (or None on failure).
    Dispatches to the platform-specific sampler.
    """
    return (_run_and_sample_macos if IS_MAC else _run_and_sample_linux)(
        binary, model_so, duration)


def _run_and_sample_macos(binary, model_so, duration):
    proc, out_f, err_f = _spawn_workload(binary, model_so, duration)
    if proc is None:
        return None
    print(f"Sampling for {duration}s -> {SAMPLE_FILE_PATH}")
    try:
        subprocess.run(
            ["sample", str(proc.pid), str(duration),
             "-f", SAMPLE_FILE_PATH],
            timeout=duration + 10, capture_output=True)
    except subprocess.TimeoutExpired:
        pass
    _wait_workload(proc, out_f, err_f)
    if not os.path.exists(SAMPLE_FILE_PATH):
        print("Error: sample produced no output file.")
        return None
    return SAMPLE_FILE_PATH


def _run_and_sample_linux(binary, model_so, duration):
    """Linux equivalent of the macOS `sample` flow.

    Strategy: launch the workload, snapshot /proc/<pid>/maps so we can
    later resolve the .so's runtime base (the macOS path gets this from
    sample's `Binary Images:` block; Linux perf records it as MMAP
    events but reading it directly from /proc is simpler), then run
    `perf record` against the live PID and convert the result to text
    with `perf script`.
    """
    proc, out_f, err_f = _spawn_workload(binary, model_so, duration)
    if proc is None:
        return None

    # Snapshot /proc/<pid>/maps now, while the process is still
    # running — once it exits, the entry is gone. Used later by
    # _extract_runtime_base_linux to find the .so's load address.
    try:
        with open(f"/proc/{proc.pid}/maps") as fm:
            maps_content = fm.read()
        with open(LINUX_MAPS_PATH, "w") as fout:
            fout.write(maps_content)
    except OSError as e:
        print(f"Warning: could not read /proc/{proc.pid}/maps: {e}")

    print(f"Sampling for {duration}s with `perf record` -> "
          f"{LINUX_PERF_DATA_PATH}")
    perf_record = [
        "perf", "record", "-F", "1000", "-g",
        "-p", str(proc.pid),
        "-o", LINUX_PERF_DATA_PATH,
        "--", "sleep", str(duration),
    ]
    try:
        r = subprocess.run(perf_record, timeout=duration + 30,
                           capture_output=True, text=True)
        if r.returncode != 0:
            print("--- perf record stderr ---")
            print(r.stderr)
            _wait_workload(proc, out_f, err_f)
            return None
    except FileNotFoundError:
        _wait_workload(proc, out_f, err_f)
        sys.exit("Error: `perf` not found. Install linux-perf "
                 "(Ubuntu: `sudo apt install linux-tools-common "
                 "linux-tools-$(uname -r)`).")
    except subprocess.TimeoutExpired:
        pass

    # Resolve the recorded data into a textual form we can parse.
    print(f"Converting via `perf script` -> {SAMPLE_FILE_PATH}")
    with open(SAMPLE_FILE_PATH, "w") as fout:
        r = subprocess.run(
            ["perf", "script", "-i", LINUX_PERF_DATA_PATH],
            stdout=fout, stderr=subprocess.PIPE, text=True)
    if r.returncode != 0:
        print("--- perf script stderr ---")
        print(r.stderr)
        _wait_workload(proc, out_f, err_f)
        return None

    _wait_workload(proc, out_f, err_f)
    if not os.path.exists(SAMPLE_FILE_PATH) \
            or os.path.getsize(SAMPLE_FILE_PATH) == 0:
        print("Error: perf script produced no output.")
        return None
    return SAMPLE_FILE_PATH


# A line in the call graph looks like one of:
#   "<indent><count> <symbol>  (in <binary>) + <off>  [0xPC]"      (leader)
#   "<indent>+ <count> <symbol>  (in <binary>) ..."                (one deeper)
#   "<indent>+   <count> <symbol>  (in <binary>) ..."              (two deeper)
#   "<indent>+   ! <count> <symbol>  (in <binary>) ..."            (collapsed)
# macOS `sample` encodes depth via the column position of the count
# digit, NOT just the leading indent: extra spaces after a '+' marker,
# and the optional '!' collapse marker, also push the count column
# rightward. We capture all the prefix material (indent / '+'/spaces /
# '!'/space) so depth = m.start('count') correctly reflects the tree
# level — using just the indent length collapses every '+' line to the
# same depth regardless of its actual logical depth.
_CG_LINE_RE = re.compile(
    r'^(?P<prefix>\s*(?:\+\s+)?(?:!\s+)?)'
    r'(?P<count>\d+)\s+(?P<symbol>.+?)'
    r'\s+\(in (?P<binary>[^)]+)\)'
    r'(?:[^\[]*\[(?P<pcs>[^\]]+)\])?',
    re.IGNORECASE)

_THREAD_RE = re.compile(r'^\s*(\d+)\s+Thread_\d+')


def _parse_pc_list(s):
    """Pull integer PCs out of a `[0x...,0x...,...]` trailer.

    `sample` collapses sibling PCs into a comma list and may end with a
    literal "..." truncation token; we drop that and any non-`0x...`
    junk. Returns (pc_list, truncated_flag).
    """
    if not s:
        return [], False
    raw = [p.strip() for p in s.split(',')]
    truncated = any(p.startswith('.') for p in raw)
    pcs = [int(p, 16) for p in raw if p.startswith('0x')]
    return pcs, truncated


def parse_call_graph(sample_file):
    """Return a list of Frame namedtuples in document/DFS order.

    On macOS the input is `sample`'s pre-aggregated call-graph tree
    text. On Linux it's `perf script`'s flat list of (one-stack-per-
    block) samples that we aggregate into the same Frame shape so all
    downstream extractors stay platform-agnostic.
    """
    return (_parse_call_graph_macos if IS_MAC
            else _parse_call_graph_linux)(sample_file)


def _parse_call_graph_macos(sample_file):
    """Parse macOS `sample`'s Call graph: section into Frame list.
    Depth combines indentation with the +-continuation marker so that
    '+' children sit one level deeper than the leader they follow.
    """
    parsed = []
    in_call_graph = False
    with open(sample_file) as f:
        for line in f:
            if line.startswith('Call graph:'):
                in_call_graph = True
                continue
            if in_call_graph and (line.startswith('Total number in stack')
                                  or line.startswith('Binary Images:')):
                break
            if not in_call_graph:
                continue
            m = _CG_LINE_RE.match(line)
            if not m:
                continue
            depth = m.start('count')
            pcs, _ = _parse_pc_list(m.group('pcs'))
            parsed.append(Frame(
                depth=depth,
                count=int(m.group('count')),
                symbol=m.group('symbol').strip(),
                binary=m.group('binary').strip(),
                pcs=pcs,
            ))
    return parsed


# perf script frame line: leading whitespace, hex PC, symbol, "(binary)".
# Examples we need to handle:
#   "    7f1234abcd main_graph_foo+0x10 (/path/to/model.so)"
#   "          ffffffff [unknown] ([kernel.kallsyms])"
# The symbol part may include "+0x..." offset which we strip; binary is
# the path inside the trailing parentheses (we keep just the basename
# so it matches what extract_runtime_base returns).
_PERF_FRAME_RE = re.compile(
    r'^\s+([0-9a-f]+)\s+(.+?)\s+\((.+?)\)\s*$', re.IGNORECASE)
# Header lines ("binary 12345 [001] 1234.567890: cpu-clock:") are
# implicitly skipped — they don't match _PERF_FRAME_RE — so we don't
# need to recognize them; only blank lines separate sample blocks.


def _parse_call_graph_linux(sample_file):
    """Parse `perf script` output into a Frame list compatible with the
    macOS path. Each blank-line-separated block is one stack sample;
    frames inside are leaf-first (deepest first). We build a virtual
    call tree by inserting each stack root-to-leaf and accumulating
    counts at each unique (symbol, binary) path; a DFS over the result
    yields the Frame list extractors expect.
    """
    stacks = _read_perf_stacks(sample_file)
    return _stacks_to_frames(stacks)


def _read_perf_stacks(sample_file):
    """Yield (weight, [(pc, symbol, binary)]) tuples — one per stack
    block in `perf script` output. Weight is 1 per sample at the
    default `-F 1000` rate; if the user re-records with a different
    frequency the weights still stay at 1, which is the right thing
    (each block IS one sample regardless of the recording rate).
    """
    stacks = []
    current = []  # list of (pc, symbol, binary), leaf first
    with open(sample_file) as f:
        for line in f:
            if not line.strip():
                if current:
                    stacks.append((1, current))
                    current = []
                continue
            m = _PERF_FRAME_RE.match(line)
            if m:
                pc = int(m.group(1), 16)
                sym = m.group(2).strip()
                # Strip "+0x..." offset suffix that perf script always
                # appends. Keep the bare symbol so the inside-marker
                # match (`symbol == "invoke_run"`) works.
                sym = re.sub(r'\+0x[0-9a-f]+$', '', sym)
                binary = os.path.basename(m.group(3).strip())
                current.append((pc, sym, binary))
            # Header lines (and anything else) are skipped silently;
            # they only matter for separating blocks via the blank
            # lines that follow each one.
    if current:
        stacks.append((1, current))
    return stacks


def _stacks_to_frames(stacks):
    """Aggregate a flat list of (weight, [frames]) into a virtual
    call tree, then DFS-emit Frame namedtuples in document order.
    Depth is the position from the root (1 = outermost frame); the
    extractors only require monotonic-on-descend depth.
    """
    # Each tree node: dict with 'count', 'pcs' (list — duplicates fine,
    # _parse_pc_list-style consumers de-dup), 'children'
    # ((symbol, binary) -> child node), 'symbol', 'binary'.
    root = {'count': 0, 'pcs': [], 'children': {},
            'symbol': '<root>', 'binary': '<root>'}
    for weight, frames in stacks:
        # frames are leaf-first; reverse for root-first descent.
        node = root
        for pc, sym, bin_ in reversed(frames):
            key = (sym, bin_)
            child = node['children'].get(key)
            if child is None:
                child = {'count': 0, 'pcs': [], 'children': {},
                         'symbol': sym, 'binary': bin_}
                node['children'][key] = child
            child['count'] += weight
            child['pcs'].append(pc)
            node = child

    out = []

    def visit(node, depth):
        if depth > 0:
            # De-dup PCs so a hot frame doesn't blow up the per-PC
            # weight when the same address recurred in many samples
            # (the offset_counts walk distributes the frame weight
            # evenly across visible PCs, so duplicates would skew it).
            unique_pcs = sorted(set(node['pcs']))
            out.append(Frame(
                depth=depth,
                count=node['count'],
                symbol=node['symbol'],
                binary=node['binary'],
                pcs=unique_pcs,
            ))
        for child in node['children'].values():
            visit(child, depth + 1)

    visit(root, 0)
    return out


def extract_total_sample_count(sample_file):
    """Total samples across the captured run.

    On macOS this sums the per-thread counts that `sample` prints at
    the top of each thread's call graph. On Linux it counts the number
    of stack blocks in `perf script` output (each block is one sample).
    """
    return (_extract_total_sample_count_macos if IS_MAC
            else _extract_total_sample_count_linux)(sample_file)


def _extract_total_sample_count_macos(sample_file):
    total = 0
    with open(sample_file) as f:
        for line in f:
            m = _THREAD_RE.match(line)
            if m:
                total += int(m.group(1))
    return total


def _extract_total_sample_count_linux(sample_file):
    # Each non-empty run of frame lines, terminated by a blank line, is
    # one sample. Count transitions from in-block to out-of-block.
    count = 0
    in_block = False
    with open(sample_file) as f:
        for line in f:
            if line.strip():
                in_block = True
            elif in_block:
                count += 1
                in_block = False
    if in_block:
        count += 1
    return count


def extract_inside_marker_count(parsed, marker=INSIDE_MARKER):
    """Count samples whose stack contains a frame named `marker`.

    We walk the call graph as a tree (via the depth column from
    parse_call_graph). Every time we descend into a frame whose symbol
    matches the marker AND whose ancestors did NOT already match, we add
    that frame's count to the total — that's the entry-point count of
    samples passing through the marker for the first time. Subsequent
    expansions of the same samples (deeper '+' frames) are skipped via
    the in-marker-subtree flag, which prevents double counting.
    """
    total = 0
    # Stack of (depth, in_marker_subtree_already)
    stack = []
    for f in parsed:
        while stack and stack[-1][0] >= f.depth:
            stack.pop()
        parent_in = stack[-1][1] if stack else False
        is_marker = (f.symbol == marker)
        in_subtree = parent_in or is_marker
        if is_marker and not parent_in:
            total += f.count
        stack.append((f.depth, in_subtree))
    return total


def extract_per_binary_leaf_counts(parsed):
    """Per-binary count of leaf call-tree frames.

    Each sample produces one stack ending at one leaf PC; that leaf
    carries the sample's count. Internal nodes carry the same count
    cumulatively, so summing everything double-counts. To get a clean
    per-binary breakdown that sums to roughly total_samples, attribute
    each frame's "leaf samples" — count minus the sum of its children's
    counts — to its binary.
    """
    counts = {}
    # frames: list of [depth, count, binary, children_sum]
    stack = []

    def close(frame):
        _, fcount, fbinary, fcsum = frame
        leaf = fcount - fcsum
        if leaf > 0:
            counts[fbinary] = counts.get(fbinary, 0) + leaf

    for f in parsed:
        while stack and stack[-1][0] >= f.depth:
            close(stack.pop())
        if stack:
            stack[-1][3] += f.count
        stack.append([f.depth, f.count, f.binary, 0])
    while stack:
        close(stack.pop())
    return counts


def extract_top_inside_symbols(parsed, marker=INSIDE_MARKER, limit=20):
    """Top-N (symbol, binary) leaves under the marker by leaf samples.

    Same leaf logic as extract_per_binary_leaf_counts, but keyed by
    (symbol, binary) and only counting frames that sit inside the
    marker's subtree. Useful for at-a-glance "where in the model is
    time spent" without disassembling the .so.
    """
    counts = {}
    stack = []  # [depth, count, symbol, binary, children_sum, in_subtree]

    def close(frame):
        _depth, fcount, fsymbol, fbinary, fcsum, fin = frame
        if not fin:
            return
        leaf = fcount - fcsum
        if leaf > 0:
            key = (fsymbol, fbinary)
            counts[key] = counts.get(key, 0) + leaf

    for f in parsed:
        while stack and stack[-1][0] >= f.depth:
            close(stack.pop())
        parent_in = stack[-1][5] if stack else False
        in_subtree = parent_in or (f.symbol == marker)
        if stack:
            stack[-1][4] += f.count
        stack.append([f.depth, f.count, f.symbol, f.binary, 0, in_subtree])
    while stack:
        close(stack.pop())

    items = sorted(counts.items(), key=lambda kv: -kv[1])
    return items[:limit]


def extract_runtime_base(sample_file, so_name):
    """Runtime base address of the .so during the sampled run.

    Subtracting this from a sampled PC gives the in-image offset, which
    is what objdump addresses are keyed on (modulo __TEXT vmaddr — see
    get_load_address). Returns 0 if not found.
    """
    return (_extract_runtime_base_macos if IS_MAC
            else _extract_runtime_base_linux)(sample_file, so_name)


def _extract_runtime_base_macos(sample_file, so_name):
    """Parse macOS sample's `Binary Images:` block, e.g.:
        "0x300000000 - 0x342... +model.so <UUID> /path/to/model.so"
    """
    with open(sample_file) as f:
        content = f.read()
    base_re = re.compile(
        rf'0x([0-9a-f]+)\s+-\s+0x[0-9a-f]+\s+\+?{re.escape(so_name)}\b',
        re.IGNORECASE)
    m = base_re.search(content)
    if not m:
        return 0
    return int(m.group(1), 16)


def _extract_runtime_base_linux(sample_file, so_name):
    """Parse the /proc/<pid>/maps snapshot captured at sample time.

    /proc/<pid>/maps lines look like:
        7f0c12345000-7f0c12def000 r-xp 00000000 fd:01 12345 /path/model.so
    A single .so produces several entries (one per ELF segment). The
    .text segment is `r-xp` (or `r-x-`); we pick the lowest start
    address with `x` in its permission bits and subtract the file
    offset, which gives the .so's image base — the same number macOS
    `sample` reports in its Binary Images section.
    """
    maps_path = sample_file + ".maps"
    if not os.path.exists(maps_path):
        # Fallback: also recognize a sidecar at the canonical path so
        # an older sample file paired with the latest run still works.
        if os.path.exists(LINUX_MAPS_PATH):
            maps_path = LINUX_MAPS_PATH
        else:
            return 0

    line_re = re.compile(
        r'^([0-9a-f]+)-[0-9a-f]+\s+(\S+)\s+([0-9a-f]+)\s+\S+\s+\S+\s+(\S+)$',
        re.IGNORECASE)
    best = None
    try:
        with open(maps_path) as f:
            for line in f:
                m = line_re.match(line.strip())
                if not m:
                    continue
                perms = m.group(2)
                if 'x' not in perms:
                    continue
                path = m.group(4)
                if os.path.basename(path) != so_name:
                    continue
                start = int(m.group(1), 16)
                file_off = int(m.group(3), 16)
                base = start - file_off
                if best is None or base < best:
                    best = base
    except OSError:
        return 0
    return best or 0


def extract_offset_counts_inside_marker(parsed, runtime_base, so_name,
                                        marker=INSIDE_MARKER):
    """Per-PC counts within model.so, restricted to the marker subtree.

    Walks the call graph as a tree, tracks "are we inside the marker's
    subtree", and for every line that (a) is in the subtree and (b)
    references model.so by name, distributes the line's weight uniformly
    across the bracketed PCs and accumulates by `pc - runtime_base`.

    Continuation '+' lines collapse multiple sibling leaves into one row
    with a comma-list of PCs; we have no per-PC weight, so the line
    weight is split evenly. Truncated PC lists ('...') under-attribute
    weight to those leaves but the line total is preserved on the visible
    PCs (integer division remainder pinned to the first PC).
    """
    counts = {}
    stack = []  # (depth, in_marker_subtree)
    for f in parsed:
        while stack and stack[-1][0] >= f.depth:
            stack.pop()
        parent_in = stack[-1][1] if stack else False
        in_subtree = parent_in or (f.symbol == marker)
        stack.append((f.depth, in_subtree))
        if not in_subtree or f.binary != so_name or not f.pcs:
            continue
        n = len(f.pcs)
        base = f.count // n
        rem = f.count - base * n
        for i, pc in enumerate(f.pcs):
            offset = pc - runtime_base
            counts[offset] = counts.get(offset, 0) + base + (rem if i == 0 else 0)
    return counts


def get_load_address(so_path):
    """Address that objdump uses as the base for instruction addresses.

    Almost always 0 for dynamically-loaded libraries on both platforms,
    but we read it for correctness against any non-zero base.
    """
    return (_get_load_address_macos if IS_MAC
            else _get_load_address_linux)(so_path)


def _get_load_address_macos(so_path):
    """__TEXT segment vmaddr from `otool -l`."""
    r = subprocess.run(["otool", "-l", so_path],
                       capture_output=True, text=True)
    if r.returncode != 0:
        return 0
    lines = r.stdout.split('\n')
    for i, line in enumerate(lines):
        if 'LC_SEGMENT_64' in line and i + 1 < len(lines) \
                and '__TEXT' in lines[i + 1]:
            for j in range(i, min(i + 10, len(lines))):
                m = re.search(r'vmaddr\s+0x([0-9a-f]+)', lines[j])
                if m:
                    return int(m.group(1), 16)
    return 0


def _get_load_address_linux(so_path):
    """First PT_LOAD's VirtAddr from `readelf -lW`. For a typical
    PIE/shared object this is 0; some toolchains emit a small base
    (e.g. 0x1000) so we don't hard-code zero.
    """
    r = subprocess.run(["readelf", "-lW", so_path],
                       capture_output=True, text=True)
    if r.returncode != 0:
        return 0
    # readelf -l format (we only need the first LOAD entry):
    #   "  LOAD   0x000000 0x0000000000000000 0x... 0x... 0x... R E 0x10000"
    for line in r.stdout.splitlines():
        m = re.match(r'\s+LOAD\s+0x[0-9a-f]+\s+0x([0-9a-f]+)',
                     line, re.IGNORECASE)
        if m:
            return int(m.group(1), 16)
    return 0


# objdump line on macOS arm64 looks like:
#   "     67c: 6d0133ed     \tstp\td13, d12, [sp, #0x10]"
# i.e. <addr>:<spaces><packed-hex-bytes><spaces>\t<mnemonic>\t<operands>.
# Bytes can be packed (`6d0133ed`) or space-separated (`6d 01 33 ed`)
# depending on toolchain version; the TAB before the mnemonic is the
# reliable delimiter. We capture the operand tail too so the OMIP
# dataflow pass can resolve adrp/add/mov chains.
_INSTR_RE = re.compile(
    r'^\s*([0-9a-f]+):[^\t\n]*\t(\S+)(?:\t([^\n]*))?',
    re.IGNORECASE)


def disassemble_so(so_path):
    """Run `objdump -d` on the .so and return {addr: (mnemonic, operands)}.

    Slow on big models (a few seconds for a 300 MB .so) — caller may
    want to cache the result. Mnemonics keep their .Nx /.Nb suffixes
    (e.g. `ldr.16b`, `fmla.4s`); the report aggregator strips them so
    the per-family histogram collapses size variants. Operands are kept
    raw including objdump's trailing `<symbol+off>` annotations.
    """
    print(f"Disassembling {so_path} ...")
    r = subprocess.run(["objdump", "-d", so_path],
                       capture_output=True, text=True)
    if r.returncode != 0:
        print(f"Error: objdump failed: {r.stderr.strip()[:200]}")
        return {}
    instructions = {}
    for line in r.stdout.split('\n'):
        m = _INSTR_RE.match(line)
        if m:
            ops = m.group(3) or ''
            instructions[int(m.group(1), 16)] = (m.group(2), ops.rstrip())
    print(f"  disassembled {len(instructions)} instructions")
    return instructions


def map_offsets_to_mnemonics(offset_counts, instructions, load_addr):
    """Aggregate offset_counts by base instruction mnemonic.

    `instr_addr = offset + load_addr` is the address objdump printed.
    Mnemonics are aggregated by their base form (everything before the
    first '.'), so `ldr.4s` and `ldr.16b` both count under `ldr`. PCs
    that don't land on a known instruction address are skipped (this
    happens for e.g. data words inside a code section).

    Returns (mnem_counts, mapped_total, unmapped_total).
    """
    mnem_counts = {}
    mapped = 0
    unmapped = 0
    for offset, count in offset_counts.items():
        instr_addr = offset + load_addr
        entry = instructions.get(instr_addr)
        if entry is None:
            unmapped += count
            continue
        mnem = entry[0] if isinstance(entry, tuple) else entry
        base = mnem.split('.')[0]
        mnem_counts[base] = mnem_counts.get(base, 0) + count
        mapped += count
    return mnem_counts, mapped, unmapped


def print_instruction_mix(mnem_counts, mapped_total, unmapped_total, limit=40):
    if not mnem_counts:
        print("  (no instruction samples to report)")
        return
    print(f"\nInstruction mix inside model.so "
          f"(mapped {mapped_total} / unmapped {unmapped_total}):")
    print(f"  {'#':>3}  {'count':>10}  {'pct':>6}  mnemonic")
    items = sorted(mnem_counts.items(), key=lambda kv: -kv[1])
    denom = mapped_total or 1
    for i, (mnem, c) in enumerate(items[:limit], 1):
        print(f"  {i:>3}  {c:>10}  {100.0 * c / denom:5.1f}%  {mnem}")
    if len(items) > limit:
        rest = sum(c for _, c in items[limit:])
        print(f"  ... {len(items) - limit} more mnemonics, "
              f"{rest} samples ({100.0 * rest / denom:.1f}%)")


# ---- Per-ONNX-op attribution via OMInstrumentPoint marker calls ------
#
# When model.so is compiled with `--profile-ir`, the compiler emits
#     void OMInstrumentPoint(const char *opName, int64_t iTag,
#                            const char *nodeName);
# calls in pairs around every ONNX op (one "before", one "after").
# We can recover the (opName, nodeName) at each call by static dataflow:
# the strings are C literals in __TEXT,__const, and the registers x0
# (opName) and x2 (nodeName) are set up by the standard arm64 pattern
#     adrp xN, page          ; high bits
#     add  xN, xN, #imm      ; low 12 bits
#     ...
#     mov  x0, xN            ; (or x2, xM)
#     bl   _OMInstrumentPoint
# Once we have the (opName, nodeName, pc) tuples, sorting by pc and
# pairing consecutive same-nodeName calls partitions the function into
# op-body spans. Sample weights from offset_counts that fall into each
# span are attributed to that op type.

OMIP_SYMBOL = "_OMInstrumentPoint"


def _load_const_section(so_path):
    """Return (vmaddr, fileoff, blob) describing the read-only data
    section that holds C-string literals — Mach-O `__TEXT,__const` on
    macOS, ELF `.rodata` on Linux — so callers can read a C-string at
    a given virtual address. Returns None if the section can't be
    located.
    """
    return (_load_const_section_macos if IS_MAC
            else _load_const_section_linux)(so_path)


def _load_const_section_macos(so_path):
    r = subprocess.run(["otool", "-l", so_path],
                       capture_output=True, text=True)
    if r.returncode != 0:
        return None
    sections = []
    cur = {}
    for ln in r.stdout.splitlines():
        s = ln.strip()
        if s.startswith('Section'):
            if cur:
                sections.append(cur)
            cur = {}
        elif s.startswith('sectname '):
            cur['sectname'] = s.split()[1]
        elif s.startswith('segname '):
            cur['segname'] = s.split()[1]
        elif s.startswith('addr '):
            try:
                cur['addr'] = int(s.split()[1], 16)
            except (ValueError, IndexError):
                pass
        elif s.startswith('offset '):
            try:
                cur['offset'] = int(s.split()[1])
            except (ValueError, IndexError):
                pass
    if cur:
        sections.append(cur)
    const = next((s for s in sections
                  if s.get('segname') == '__TEXT'
                  and s.get('sectname') == '__const'), None)
    if not const or 'addr' not in const or 'offset' not in const:
        return None
    with open(so_path, 'rb') as fh:
        blob = fh.read()
    return (const['addr'], const['offset'], blob)


# readelf -SW row example (the W flag forces a single line per section):
#   "  [13] .rodata   PROGBITS  0000000000003000 003000 000abc 00 A 0 0 16"
# The columns we want — addr, offset, size — are positionally fixed at
# 4/5/6 after the section name; using -W keeps them on one line.
_READELF_SECTION_RE = re.compile(
    r'^\s*\[\s*\d+\s*\]\s+(\S+)\s+\S+\s+'
    r'([0-9a-f]+)\s+([0-9a-f]+)\s+([0-9a-f]+)',
    re.IGNORECASE)


def _load_const_section_linux(so_path):
    r = subprocess.run(["readelf", "-SW", so_path],
                       capture_output=True, text=True)
    if r.returncode != 0:
        return None
    rodata = None
    for line in r.stdout.splitlines():
        m = _READELF_SECTION_RE.match(line)
        if m and m.group(1) == '.rodata':
            rodata = (int(m.group(2), 16),     # vmaddr
                      int(m.group(3), 16),     # file offset
                      int(m.group(4), 16))     # size
            break
    if rodata is None:
        return None
    with open(so_path, 'rb') as fh:
        blob = fh.read()
    return (rodata[0], rodata[1], blob)


def _read_cstring(const_info, va, max_len=512):
    """Read a NUL-terminated C-string at virtual address `va`. Returns
    None if `va` is outside the section we know how to read.
    """
    if const_info is None:
        return None
    vmaddr, fileoff, blob = const_info
    file_off = fileoff + (va - vmaddr)
    if file_off < 0 or file_off >= len(blob):
        return None
    end = blob.find(b'\x00', file_off, file_off + max_len)
    if end < 0:
        return None
    try:
        return blob[file_off:end].decode('utf-8')
    except UnicodeDecodeError:
        return None


# Strip objdump's trailing "<symbol+off>" annotation from operand text
# so register-name parsing isn't fooled by names containing commas.
_OPS_ANNOT_RE = re.compile(r'\s*<[^>]*>\s*$')


def _clean_ops(ops):
    return _OPS_ANNOT_RE.sub('', ops or '').strip()


# Dataflow pass: walk instructions in PC order, track which registers
# hold known-value VAs (computed from adrp+add pairs and propagated
# through `mov dst, src`). At each `bl _OMInstrumentPoint`, snapshot
# x0 and x2. Any other instruction that writes a tracked register
# kills its value (conservative).
_ADRP_RE = re.compile(r'^\s*(x\d+)\s*,\s*0x([0-9a-f]+)', re.IGNORECASE)
_ADD_IMM_RE = re.compile(
    r'^\s*(x\d+)\s*,\s*(x\d+)\s*,\s*#0x([0-9a-f]+)\s*$', re.IGNORECASE)
_MOV_RR_RE = re.compile(
    r'^\s*(x\d+|w\d+)\s*,\s*(x\d+|w\d+)\s*$', re.IGNORECASE)
_FIRST_REG_RE = re.compile(r'^\s*(x\d+|w\d+)\b', re.IGNORECASE)

# Instructions whose first operand is a SOURCE, not a destination —
# treating these as writes would pessimistically kill our tracking.
_NON_WRITERS = {
    'cmp', 'cmn', 'tst', 'ccmp', 'ccmn',
    'str', 'strb', 'strh', 'stur', 'sturb', 'sturh',
    'stp', 'stnp',
    'cbz', 'cbnz', 'tbz', 'tbnz', 'b', 'bl', 'br', 'blr', 'ret',
    'b.eq', 'b.ne', 'b.lt', 'b.gt', 'b.le', 'b.ge',
    'b.cs', 'b.cc', 'b.hi', 'b.ls', 'b.mi', 'b.pl', 'b.vs', 'b.vc',
}

# bl clobbers x0..x18 + x29/x30 per the arm64 PCS; we reset our tracked
# values for those after every call so a stale value doesn't leak.
_BL_CLOBBER_REGS = {f'x{i}' for i in range(19)} | {'x29', 'x30'}


def extract_omip_calls(instructions, const_info):
    """Walk the disassembly and resolve (opName, nodeName) at each
    `bl _OMInstrumentPoint` call site.

    Returns a list of dicts with keys: pc, op_name, node_name,
    op_va, node_va. Either string field is None when the dataflow
    couldn't recover it (e.g. register clobbered by intervening code).
    """
    # Sort by PC so we walk in execution order. Branches/loops aren't
    # modelled — basic-block-local information only — but that's fine
    # because the OMIP setup pattern (adrp+add+...+mov+bl) always lives
    # within a single basic block.
    addrs = sorted(instructions.keys())
    reg_va = {}      # reg name -> VA the register currently holds
    pending_adrp = {}  # reg name -> page VA from the most recent adrp

    calls = []
    for pc in addrs:
        mnem, raw_ops = instructions[pc]
        ops = _clean_ops(raw_ops)
        # Lower-case mnemonic (objdump already emits lowercase, but be safe).
        m = mnem.lower()

        if m == 'adrp':
            am = _ADRP_RE.match(ops)
            if am:
                dst = am.group(1)
                pending_adrp[dst] = int(am.group(2), 16)
                reg_va.pop(dst, None)
            continue

        if m == 'add':
            am = _ADD_IMM_RE.match(ops)
            if am:
                dst, src, imm_s = am.group(1), am.group(2), am.group(3)
                if dst == src and src in pending_adrp:
                    reg_va[dst] = pending_adrp[src] + int(imm_s, 16)
                else:
                    reg_va.pop(dst, None)
                pending_adrp.pop(dst, None)
                continue
            # `add` with non-immediate operands (e.g. `add x21, x21, x4`)
            # falls through to the generic kill path below.

        if m == 'mov':
            mm = _MOV_RR_RE.match(ops)
            if mm:
                dst, src = mm.group(1), mm.group(2)
                # Only x* registers carry pointers; w* moves are 32-bit.
                if dst.startswith('x'):
                    if src in reg_va:
                        reg_va[dst] = reg_va[src]
                    else:
                        reg_va.pop(dst, None)
                pending_adrp.pop(dst, None)
                continue
            # Non-register-to-register mov (immediate) falls through.

        if m == 'bl':
            # The OMInstrumentPoint identifier lives inside the
            # `<symbol>` annotation that _clean_ops strips, so match
            # against the raw operand text here.
            if OMIP_SYMBOL in raw_ops:
                calls.append({
                    'pc': pc,
                    'op_va': reg_va.get('x0'),
                    'node_va': reg_va.get('x2'),
                    'op_name': _read_cstring(const_info, reg_va['x0'])
                                  if 'x0' in reg_va else None,
                    'node_name': _read_cstring(const_info, reg_va['x2'])
                                  if 'x2' in reg_va else None,
                })
            for r in _BL_CLOBBER_REGS:
                reg_va.pop(r, None)
                pending_adrp.pop(r, None)
            continue

        # Generic kill path: any instruction whose first operand is a
        # register and whose mnemonic is not in the non-writer set
        # invalidates that register. False positives (e.g. fancy load
        # forms) only cost precision, not correctness.
        if m in _NON_WRITERS:
            continue
        rm = _FIRST_REG_RE.match(ops)
        if rm:
            reg = rm.group(1)
            if reg.startswith('w'):
                # w<N> writes alias x<N>'s low half + zeroes high half.
                reg = 'x' + reg[1:]
            reg_va.pop(reg, None)
            pending_adrp.pop(reg, None)

    return calls


def build_op_spans(calls):
    """Pair OMIP calls into (begin, end) per ONNX op and return ordered
    spans. Pairing rule: walk calls in PC order; consecutive calls with
    matching node_name form a (begin, end) pair. Calls that don't pair
    cleanly are dropped from the span list (but kept in the unpaired
    count so the caller can surface them).

    Each span is a dict: {op_name, node_name, begin_pc, end_pc, body_pc}
    where body_pc is begin_pc + 4 (the first instruction strictly after
    the begin call's `bl`).
    """
    spans = []
    unpaired = 0
    i = 0
    while i < len(calls):
        c = calls[i]
        if c['node_name'] is None:
            unpaired += 1
            i += 1
            continue
        if i + 1 < len(calls) and calls[i + 1]['node_name'] == c['node_name']:
            end = calls[i + 1]
            spans.append({
                'op_name': c['op_name'] or '<unknown>',
                'node_name': c['node_name'],
                'begin_pc': c['pc'],
                'end_pc': end['pc'],
                'body_pc': c['pc'] + 4,
            })
            i += 2
        else:
            unpaired += 1
            i += 1
    return spans, unpaired


def filter_offsets_by_op_regex(offset_counts, spans, load_addr, op_regex,
                               invert=False):
    """Return the subset of offset_counts whose PCs fall inside an op
    span whose op_name matches `op_regex` (re.search, so a substring
    pattern works without `.*` boilerplate). When `invert` is True,
    keep spans whose op_name does NOT match instead — used by
    `--not-op REGEX` to exclude families of ops from the mix.

    Also returns the list of matched spans and the set of distinct
    matching op names so the caller can tell the user what got selected.
    """
    flag_name = '--not-op' if invert else '--op'
    try:
        pat = re.compile(op_regex)
    except re.error as e:
        sys.exit(f"Error: {flag_name} regex {op_regex!r} is invalid: {e}")
    if invert:
        matched = [s for s in spans if not pat.search(s['op_name'])]
    else:
        matched = [s for s in spans if pat.search(s['op_name'])]
    if not matched:
        return {}, [], set()

    matched_sorted = sorted(matched, key=lambda s: s['body_pc'])
    body_pcs = [s['body_pc'] for s in matched_sorted]
    end_pcs = [s['end_pc'] for s in matched_sorted]

    import bisect
    out = {}
    for offset, count in offset_counts.items():
        addr = offset + load_addr
        idx = bisect.bisect_right(body_pcs, addr) - 1
        if idx < 0 or addr >= end_pcs[idx]:
            continue
        out[offset] = count
    matched_names = {s['op_name'] for s in matched}
    return out, matched_sorted, matched_names


def attribute_offsets_to_ops(offset_counts, spans, load_addr):
    """For every (offset, count) in offset_counts, find the span whose
    [body_pc, end_pc) covers `offset + load_addr` and add the count to
    that op. Returns:
      per_op: dict[op_name -> total samples]
      per_op_mnem_acc: dict[op_name -> dict[offset -> count]] for a
        later instruction-mix breakdown
      attributed_total, unattributed_total
    """
    if not spans:
        return {}, {}, 0, sum(offset_counts.values())

    # Sort spans by body_pc and binary-search for each offset.
    spans_sorted = sorted(spans, key=lambda s: s['body_pc'])
    body_pcs = [s['body_pc'] for s in spans_sorted]
    end_pcs = [s['end_pc'] for s in spans_sorted]
    op_names = [s['op_name'] for s in spans_sorted]

    import bisect
    per_op = {}
    per_op_offsets = {}
    attributed = 0
    unattributed = 0
    for offset, count in offset_counts.items():
        addr = offset + load_addr
        # Largest body_pc <= addr.
        idx = bisect.bisect_right(body_pcs, addr) - 1
        if idx < 0 or addr >= end_pcs[idx]:
            unattributed += count
            continue
        op = op_names[idx]
        per_op[op] = per_op.get(op, 0) + count
        d = per_op_offsets.setdefault(op, {})
        d[offset] = d.get(offset, 0) + count
        attributed += count
    return per_op, per_op_offsets, attributed, unattributed


def print_per_op_report(per_op_counts, attributed, unattributed, limit=40):
    if not per_op_counts:
        print("\n(no per-op attribution; OMInstrumentPoint markers not "
              "found — was the model compiled with --profile-ir?)")
        return
    print(f"\nPer-ONNX-op samples "
          f"(attributed {attributed} / unattributed {unattributed}):")
    print(f"  {'#':>3}  {'count':>10}  {'pct':>6}  op")
    items = sorted(per_op_counts.items(), key=lambda kv: -kv[1])
    denom = attributed or 1
    for i, (op, c) in enumerate(items[:limit], 1):
        print(f"  {i:>3}  {c:>10}  {100.0 * c / denom:5.1f}%  {op}")
    if len(items) > limit:
        rest = sum(c for _, c in items[limit:])
        print(f"  ... {len(items) - limit} more ops, "
              f"{rest} samples ({100.0 * rest / denom:.1f}%)")


def print_per_op_instruction_mix(per_op_offsets, instructions, load_addr,
                                 top_ops=8, top_mnems=8):
    """For the top-K ops by sample count, show their instruction mix."""
    if not per_op_offsets:
        return
    op_totals = sorted(
        ((op, sum(d.values())) for op, d in per_op_offsets.items()),
        key=lambda kv: -kv[1])[:top_ops]
    print(f"\nTop {len(op_totals)} ops — instruction mix:")
    for op, total in op_totals:
        offsets = per_op_offsets[op]
        mnem_counts = {}
        for off, c in offsets.items():
            entry = instructions.get(off + load_addr)
            if entry is None:
                continue
            mnem = entry[0] if isinstance(entry, tuple) else entry
            base = mnem.split('.')[0]
            mnem_counts[base] = mnem_counts.get(base, 0) + c
        items = sorted(mnem_counts.items(), key=lambda kv: -kv[1])
        denom = sum(mnem_counts.values()) or 1
        head = ', '.join(f"{m}={c}" for m, c in items[:top_mnems])
        if len(items) > top_mnems:
            head += f", +{len(items) - top_mnems} more"
        print(f"  {op:>32s}  total={total:>8d}   {head}")


def save_profile(out_path, cpp_path, binary_path, model_so, duration,
                 total_samples, inside_samples, per_binary_counts,
                 top_inside, runtime_base, load_addr, offset_counts):
    payload = {
        "version": PROFILE_FORMAT_VERSION,
        "so_path": os.path.abspath(model_so),
        "script": os.path.abspath(cpp_path),
        "binary": os.path.abspath(binary_path),
        "duration": duration,
        "timestamp": datetime.datetime.now().isoformat(timespec="seconds"),
        "inside_marker": INSIDE_MARKER,
        "total_samples": total_samples,
        "inside_samples": inside_samples,
        "per_binary_counts": per_binary_counts,
        # JSON keys must be strings; flatten (symbol, binary) tuples.
        "top_inside_symbols": [
            {"symbol": sym, "binary": b, "count": c}
            for (sym, b), c in top_inside
        ],
        # Captured for the instruction-mix step in --analyze: runtime
        # base lets us turn sampled PCs into in-image offsets, and
        # load_addr (almost always 0) shifts those onto the addresses
        # objdump prints.
        "so_runtime_base": f"0x{runtime_base:x}",
        "so_load_address": load_addr,
        # Decimal-string keys (JSON requirement); values are sample
        # weights distributed across visible PCs by the call-graph walk.
        "offset_counts": {str(k): v for k, v in offset_counts.items()},
    }
    with open(out_path, "w") as f:
        json.dump(payload, f, indent=2)
    print(f"\nWrote profile: {out_path}")


def print_report(total_samples, inside_samples, per_binary_counts, top_inside):
    if total_samples:
        outside = total_samples - inside_samples
        in_pct = 100.0 * inside_samples / total_samples
        out_pct = 100.0 * outside / total_samples
        print(f"\nSamples (using `{INSIDE_MARKER}` as inside-model marker):")
        print(f"  total          : {total_samples}")
        print(f"  inside model   : {inside_samples} ({in_pct:.1f}%)")
        print(f"  outside model  : {outside} ({out_pct:.1f}%)")
    else:
        print(f"\nSamples: total unknown (no Thread_ lines found); "
              f"inside={inside_samples}")

    if per_binary_counts:
        items = sorted(per_binary_counts.items(), key=lambda kv: -kv[1])
        denom = sum(per_binary_counts.values()) or 1
        print(f"\nPer-binary leaf samples (decreasing):")
        print(f"  {'#':>3}  {'count':>8}  {'pct':>6}  binary")
        for i, (b, c) in enumerate(items, 1):
            print(f"  {i:>3}  {c:>8}  {100.0 * c / denom:5.1f}%  {b}")

    if top_inside:
        denom = sum(c for _, c in top_inside) or 1
        print(f"\nTop frames inside `{INSIDE_MARKER}` subtree (leaf samples):")
        print(f"  {'#':>3}  {'count':>8}  {'pct':>6}  symbol  (binary)")
        for i, ((sym, b), c) in enumerate(top_inside, 1):
            print(f"  {i:>3}  {c:>8}  {100.0 * c / denom:5.1f}%  "
                  f"{sym}  ({b})")


def analyze_profile(json_path, so_override=None, op_regex=None,
                    not_op_regex=None):
    """Re-print the report from a saved JSON profile, plus the
    instruction-mix breakdown derived from disassembling the .so.
    `so_override` lets you re-disassemble a different copy of the .so
    (e.g. one with debug info preserved) without re-recording.
    `op_regex` / `not_op_regex` (mutually exclusive) switch the
    instruction-mix output to a filtered-by-op-name view (include vs.
    exclude) and suppress the per-op sections.
    """
    if not os.path.exists(json_path):
        sys.exit(f"Error: profile JSON not found: {json_path}")
    with open(json_path) as f:
        data = json.load(f)

    print(f"Analyzing: {json_path}")
    print(f"  recorded against : {data.get('so_path')}")
    print(f"  duration         : {data.get('duration')}s")
    print(f"  inside marker    : {data.get('inside_marker', INSIDE_MARKER)}")

    top_inside = [
        ((e["symbol"], e["binary"]), e["count"])
        for e in data.get("top_inside_symbols", [])
    ]
    print_report(
        data.get("total_samples", 0),
        data.get("inside_samples", 0),
        data.get("per_binary_counts", {}),
        top_inside)

    # Instruction-mix step. Skip silently for old (v1/v2) JSONs that
    # didn't capture per-PC counts.
    offset_counts_raw = data.get("offset_counts")
    if not offset_counts_raw:
        print("\n(no offset_counts in this profile — re-record to get the "
              "instruction-mix breakdown.)")
        return
    offset_counts = {int(k): v for k, v in offset_counts_raw.items()}
    so_path = so_override or data.get("so_path")
    if not so_path or not os.path.exists(so_path):
        print(f"\nWarning: .so not found ({so_path!r}); skipping "
              "instruction mix.")
        return
    load_addr = data.get("so_load_address", 0)
    instructions = disassemble_so(so_path)
    if not instructions:
        return
    # Same gating as run mode: when --op or --not-op is set, the
    # filtered instruction mix inside run_per_op_analysis replaces the
    # unfiltered one and the per-op breakdown is skipped.
    if op_regex is None and not_op_regex is None:
        mnem_counts, mapped, unmapped = map_offsets_to_mnemonics(
            offset_counts, instructions, load_addr)
        print_instruction_mix(mnem_counts, mapped, unmapped)
    run_per_op_analysis(so_path, offset_counts, instructions, load_addr,
                        op_regex=op_regex, not_op_regex=not_op_regex)


def run_per_op_analysis(so_path, offset_counts, instructions, load_addr,
                        op_regex=None, not_op_regex=None):
    """If both op_regex and not_op_regex are None: produce the full
    per-ONNX-op breakdown (sample counts per op type + top-N op
    instruction mix).

    If exactly one is set: skip both of those and instead print a
    single instruction mix restricted to PCs that land inside op spans
    whose op_name matches (--op) or does NOT match (--not-op) the
    regex. Mutually exclusive — argparse enforces this; the assert
    here is just a defensive double-check. The caller is expected to
    skip the unfiltered instruction mix in this mode.

    Silent no-op when the .so wasn't built with --profile-ir (no
    OMInstrumentPoint markers exist).
    """
    assert not (op_regex and not_op_regex), \
        "op_regex and not_op_regex are mutually exclusive"
    # The OMIP dataflow walks arm64 `adrp + add + mov` chains; on x86_64
    # the equivalent (RIP-relative `lea` + reg moves) needs different
    # patterns we haven't ported. Bail with a clear note instead of
    # producing garbage spans.
    arch = _so_arch(so_path)
    if arch != 'arm64':
        if op_regex or not_op_regex:
            sys.exit(f"Error: --op / --not-op require per-op recovery, "
                     f"which is currently arm64-only (.so arch: {arch}).")
        print(f"\n(per-ONNX-op recovery skipped: requires arm64 .so, "
              f"got {arch})")
        return
    const_info = _load_const_section(so_path)
    if const_info is None:
        return
    calls = extract_omip_calls(instructions, const_info)
    if not calls:
        return
    spans, unpaired = build_op_spans(calls)
    print(f"\nOMInstrumentPoint markers: {len(calls)} calls, "
          f"{len(spans)} op spans, {unpaired} unpaired")
    if not spans:
        return

    active_regex = op_regex if op_regex else not_op_regex
    if active_regex is not None:
        invert = not_op_regex is not None
        flag = '--not-op' if invert else '--op'
        filtered, matched_spans, matched_names = filter_offsets_by_op_regex(
            offset_counts, spans, load_addr, active_regex, invert=invert)
        all_names = sorted({s['op_name'] for s in spans})
        if not matched_spans:
            verb = "excluded everything" if invert else "no op span name matched"
            print(f"\n{flag} {active_regex!r}: {verb}. "
                  f"Available op names include: "
                  f"{', '.join(all_names[:8])}...")
            return
        names_label = "kept" if invert else "matched"
        names_str = ', '.join(sorted(matched_names))
        print(f"\n{flag} {active_regex!r} {names_label}: {names_str} "
              f"({len(matched_spans)} spans, "
              f"{sum(filtered.values())} samples)")
        mnem_counts, mapped, unmapped = map_offsets_to_mnemonics(
            filtered, instructions, load_addr)
        print_instruction_mix(mnem_counts, mapped, unmapped)
        return

    per_op, per_op_offsets, attributed, unattributed = (
        attribute_offsets_to_ops(offset_counts, spans, load_addr))
    print_per_op_report(per_op, attributed, unattributed)
    print_per_op_instruction_mix(per_op_offsets, instructions, load_addr)


def main():
    p = argparse.ArgumentParser(
        description="Profile a statically-linked C++ inference workload "
                    "and report per-binary / per-frame sample counts, "
                    "instruction mix, and (if model.so was built with "
                    "--profile-ir) per-ONNX-op breakdowns. Detects "
                    f"inside-model samples via the `{INSIDE_MARKER}` "
                    "wrapper symbol in the call stack — the wrapper "
                    "comes from this script's embedded workload, not "
                    "the user's .cpp.",
        # Disable argparse's auto-help so we can have a -h/--help that
        # accepts an optional `init` argument to print the sample .cpp.
        add_help=False)
    p.add_argument("-h", "--help", nargs="?", const="default", default=None,
                   choices=["default", "init"],
                   metavar="[init]",
                   help="Without an argument: show this help message. "
                        "With `init`: print a sample "
                        "`initialize_model_input()` C++ implementation "
                        "you can copy-paste, edit, and pass via --init.")
    # Run-mode inputs (need both -i and -m). Analyze-mode input is -l.
    # We don't put them in argparse mutex groups because the run-mode
    # pair would need to be a single group; we validate manually below.
    p.add_argument("-i", "--init", metavar="CPP", default=None,
                   help="C++ source defining "
                        "`extern \"C\" OMTensorList *initialize_model_input(void);` "
                        "(run mode). This is the only piece you write "
                        "per model; the timing loop, argv parsing, and "
                        "invoke_run wrapper are embedded in the driver.")
    p.add_argument("-m", "--model", metavar="SO", default=None,
                   help="model.so the workload will be statically "
                        "linked against (run mode). The directory is "
                        "added to DYLD_LIBRARY_PATH at launch so dyld "
                        "can resolve the .so even if its install_name "
                        "is just a basename. May also be passed alongside "
                        "--load to override the .so used for disassembly "
                        "(useful when re-analyzing against a different "
                        "build of the same model).")
    p.add_argument("-t", "--time", type=int, default=30,
                   help="Sampling duration in seconds (default 30, "
                        "run mode only).")
    p.add_argument("-s", "--save", metavar="JSON", default=None,
                   help="Where to write the JSON profile "
                        "(default: <init_basename>.profile.json next "
                        "to the init .cpp; run mode only).")
    p.add_argument("-l", "--load", metavar="JSON", default=None,
                   help="Print the report from a previously-saved JSON, "
                        "including the instruction-mix breakdown and "
                        "per-ONNX-op attribution. Use either --load OR "
                        "the (--init, --model) pair, not both.")
    op_group = p.add_mutually_exclusive_group()
    op_group.add_argument("--op", metavar="REGEX", default=None,
                   help="Restrict the instruction mix to PCs that fall "
                        "inside ONNX op spans whose opName matches "
                        "REGEX (re.search). Suppresses the per-ONNX-op "
                        "samples and top-N ops mix; only the filtered "
                        "instruction mix is shown. Requires the .so to "
                        "be built with --profile-ir. Examples: "
                        "`--op MatMul`, `--op 'onnx\\.(MatMul|Gemm)$'`.")
    op_group.add_argument("--not-op", metavar="REGEX", default=None,
                   dest="not_op",
                   help="Inverse of --op: restrict the instruction mix "
                        "to PCs inside ONNX op spans whose opName does "
                        "NOT match REGEX. Useful for excluding the "
                        "dominant op (e.g. `--not-op MatMul`) so the "
                        "smaller ops become visible in the histogram. "
                        "Mutually exclusive with --op.")
    p.add_argument("-v", "--verbose", action="store_true",
                   help="Echo the compile command and its stderr.")
    args = p.parse_args()

    # Custom help dispatch — `-h init` prints a sample init .cpp,
    # `-h` (or no arg passed) prints the standard usage block.
    if args.help is not None:
        if args.help == "init":
            sys.stdout.write(SAMPLE_INIT_CPP)
        else:
            p.print_help()
        return

    # Mode selection: --load is analyze; (--init, --model) is run.
    # Reject mixing run-mode flags with --load except for --model,
    # which is allowed as a .so override during analyze.
    if args.load is not None:
        if args.init is not None:
            p.error("--load is mutually exclusive with --init (analyze "
                    "mode reads the cpp path from the saved JSON).")
        analyze_profile(args.load, so_override=args.model,
                        op_regex=args.op, not_op_regex=args.not_op)
        return

    if not args.init or not args.model:
        p.error("either --load <json>, or both --init <cpp> and "
                "--model <so>, must be given.")
    if not os.path.exists(args.init):
        sys.exit(f"Error: init .cpp file not found: {args.init}")
    if not os.path.exists(args.model):
        sys.exit(f"Error: model.so not found: {args.model}")

    binary = compile_workload(args.init, args.model,
                              verbose=args.verbose)

    sample_file = run_and_sample(binary, args.model, args.time)
    if sample_file is None:
        sys.exit("Sampling failed.")

    parsed = parse_call_graph(sample_file)
    if not parsed:
        sys.exit("Empty call graph in sample output.")
    total_samples = extract_total_sample_count(sample_file)
    inside_samples = extract_inside_marker_count(parsed)
    per_binary_counts = extract_per_binary_leaf_counts(parsed)
    top_inside = extract_top_inside_symbols(parsed)

    so_name = os.path.basename(args.model)
    runtime_base = extract_runtime_base(sample_file, so_name)
    load_addr = get_load_address(args.model)
    offset_counts = extract_offset_counts_inside_marker(
        parsed, runtime_base, so_name)

    if inside_samples == 0:
        print(f"Warning: no `{INSIDE_MARKER}` frames found in the call "
              "graph. The .cpp may be missing the wrapper, or it was "
              "compiled without -g, or the inference loop didn't run "
              "during the sampling window.")

    out_path = args.save or os.path.join(
        os.path.dirname(os.path.abspath(args.init)),
        os.path.splitext(os.path.basename(args.init))[0]
        + ".profile.json")
    save_profile(out_path, args.init, binary, args.model, args.time,
                 total_samples, inside_samples, per_binary_counts,
                 top_inside, runtime_base, load_addr, offset_counts)
    print_report(total_samples, inside_samples, per_binary_counts, top_inside)

    # Disassemble + map (the JSON has all the data needed to re-run
    # this part via --load later, but we always print it on the live
    # run so the user sees results without a second invocation).
    if offset_counts:
        instructions = disassemble_so(args.model)
        if instructions:
            # When --op or --not-op is set, skip the unfiltered mix —
            # the filtered one inside run_per_op_analysis replaces it.
            # The per-op breakdown is suppressed in that mode too.
            if args.op is None and args.not_op is None:
                mnem_counts, mapped, unmapped = map_offsets_to_mnemonics(
                    offset_counts, instructions, load_addr)
                print_instruction_mix(mnem_counts, mapped, unmapped)
            run_per_op_analysis(args.model, offset_counts, instructions,
                                load_addr, op_regex=args.op,
                                not_op_regex=args.not_op)


if __name__ == "__main__":
    main()

# Made with Bob
