/*
 * SPDX-License-Identifier: Apache-2.0
 */

//===----------------- RunONNXLib.cpp  ------------------------===//
//
// Copyright 2019-2026 The IBM Research Authors.
//
// =============================================================================
/*
  This file helps run an onnx model as simply as possible for testing.
  Compile as follows in the onnx-mlir build subdirectory.

  For dynamically loaded models (default):

    cd onnx-mlir/build
    sh ../utils/build-run-onnx-lib.sh
    Debug/bin/run-onnx-lib test/backend/test_add/test_add.so

  For statically loaded models:

    cd onnx-mlir/build
    sh ../utils/build-run-onnx-lib.sh test/backend/test_add/test_add.so
    Debug/bin/run-onnx-lib

  See printUsage() below for usage of the program.
*/

//===----------------------------------------------------------------------===//

// Define while compiling.
// #define LOAD_MODEL_STATICALLY 1

auto printUsage = [](auto &out, const char *name) {
#if LOAD_MODEL_STATICALLY
  out << "Usage: " << name << " [options]";
#else
  out << "Usage: " << name << " [options] model.so";
#endif
  out << R"""(

  Program will instantiate the model given by "model.so"
  with random inputs, launch the computation, and ignore
  the results. A model is typically generated by lowering
  an ONNX model using a "onnx-mlir --EmitLib model.onnx"
  command. When the input model is not found as is, the
  path to the local directory is also prepended.

  Options:
    -s STR | --shape-info STR
         Shape overrides for dynamic input dimensions.
         Format: INPUT_ID:D1xD2x...xDn, ... where INPUT_ID is an
         integer >= 0, a range (e.g. 2-5), or -1 for all inputs.
         A dim value of -1 keeps the value from the signature.
         E.g. --shape-info 0:1x10x20,1:7x5x3)""";
#if !LOAD_MODEL_STATICALLY
  out << R"""(
    -e name | --entry-point name
         Name of the ONNX model entry point.
         Default is "run_main_graph".)""";
#endif
  out << R"""(
    -i STR | --input-value STR
         Per-input data fill specification, overriding --lower-bound /
         --upper-bound for individual tensors.  Format:
           INPUT_ID:spec1 spec2 ..., ...
         where each spec is one of:
           min<num>  lower bound for random fill
           max<num>  upper bound for random fill
           val<num>  constant fill (equivalent to min=max=num)
         E.g. --input-value 0:min-1.0max1.0,1:val0
    -l STR | --lower-bound STR
         Per-type default lower bound for random fill.
         Format: typename:value, typename:value, ...
         Supported types: bool, int8, uint8, int16, uint16, int32, uint32,
           int64, uint64, float16, float32, float64.
         E.g. --lower-bound int64:-10,float32:-0.2
    -u STR | --upper-bound STR
         Per-type default upper bound for random fill.  Same format.
         E.g. --upper-bound int64:10,float32:0.2
    -k NUM | --seed NUM
         Seed for the random number generator.  Default: 42.
    -h | --help
         Print help message.
    -n NUM | --iterations NUM
         Number of times to run the tests, default 1.
    -m NUM | --meas NUM
         Measure the kernel execution time NUM times.
    -r | -reuse true|false
         Reuse input data, default on.
    -v | --verbose
         Print the shape and value range of the inputs.

  )""";
};

#include <algorithm>
#include <assert.h>
#include <cmath>
#include <cstring>
#include <dlfcn.h>
#include <getopt.h>
#include <iostream>
#include <string>
#include <vector>

// Include ONNX-MLIR Runtime support.
#include "OnnxMlirRuntime.h"
#include "src/Runtime/OMTensorHelper.hpp"
#include "src/Runtime/OMTensorListHelper.hpp"

using namespace std;

#ifdef _WIN32
// TO BE FIXED
#else
#include <sys/time.h>
#endif
// Data structure to hold measurement times (in microseconds).
vector<uint64_t> timeLogInMicroSec;

// =============================================================================
// Interface definitions — entry point and signature functions differ between
// static and DLL builds; tensor creation/destruction use the runtime directly.

extern "C" OMTensorList *run_main_graph(OMTensorList *);
extern "C" const char *omInputSignature(const char *);
extern "C" const char *omOutputSignature(const char *);
extern "C" const char *omCompilationInfo(void);

#if LOAD_MODEL_STATICALLY
#define RUN_MAIN_GRAPH      run_main_graph
#define OM_INPUT_SIGNATURE  omInputSignature
#define OM_OUTPUT_SIGNATURE omOutputSignature
#define OM_COMPILATION_INFO omCompilationInfo
#define OPTIONS "hs:i:l:u:k:n:m:vr:"
#else
OMTensorList *(*dll_run_main_graph)(OMTensorList *);
const char *(*dll_omInputSignature)(const char *);
const char *(*dll_omOutputSignature)(const char *);
const char *(*dll_omCompilationInfo)(void);
#define RUN_MAIN_GRAPH      dll_run_main_graph
#define OM_INPUT_SIGNATURE  dll_omInputSignature
#define OM_OUTPUT_SIGNATURE dll_omOutputSignature
#define OM_COMPILATION_INFO dll_omCompilationInfo
#define OPTIONS "e:hs:i:l:u:k:n:m:vr:"
#endif

// =============================================================================
// Global options — identical for static and DLL builds.

static int sIterations = 1;
static bool verbose = false;
static bool reuseInput = true;
static bool measureExecTime = false;
static string entryPointName("run_main_graph");
static string shapeInfo;
static string inputValue;
static string lowerBound;
static string upperBound;
static int seed = 42;

// =============================================================================

void usage(const char *name) {
  printUsage(cout, name);
  exit(1);
}

#if !LOAD_MODEL_STATICALLY
void loadDLL(const string &name, const string &epName) {
  cout << "Load model file " << name << " with entry point " << epName << endl;
  void *handle = dlopen(name.c_str(), RTLD_LAZY);
  if (!handle) {
    string qualifiedName = "./" + name;
    cout << "  Did not find model, try in current dir " << qualifiedName
         << endl;
    handle = dlopen(qualifiedName.c_str(), RTLD_LAZY);
  }
  assert(handle && "Error loading the model's dll file; provide a fully "
                   "qualified path if needed");
  dll_run_main_graph =
      (OMTensorList * (*)(OMTensorList *)) dlsym(handle, epName.c_str());
  assert(!dlerror() && "failed to load entry point");
  dll_omInputSignature =
      (const char *(*)(const char *))dlsym(handle, "omInputSignature");
  assert(!dlerror() && "failed to load omInputSignature");
  dll_omOutputSignature =
      (const char *(*)(const char *))dlsym(handle, "omOutputSignature");
  assert(!dlerror() && "failed to load omOutputSignature");
  dll_omCompilationInfo =
      (const char *(*)(void))dlsym(handle, "omCompilationInfo");
  assert(!dlerror() && "failed to load omCompilationInfo");
}
#endif

// =============================================================================
// Argument parsing — identical options for static and DLL builds.

void parseArgs(int argc, char **argv) {
  int c;
  static struct option long_options[] = {
      {"shape-info",  required_argument, 0, 's'},
      {"input-value", required_argument, 0, 'i'},
      {"lower-bound", required_argument, 0, 'l'},
      {"upper-bound", required_argument, 0, 'u'},
      {"seed",        required_argument, 0, 'k'},
      {"entry-point", required_argument, 0, 'e'},
      {"help",        no_argument,       0, 'h'},
      {"iterations",  required_argument, 0, 'n'},
      {"meas",        required_argument, 0, 'm'},
      {"reuse",       required_argument, 0, 'r'},
      {"verbose",     no_argument,       0, 'v'},
      {0, 0, 0, 0}};

  while (true) {
    int index = 0;
    c = getopt_long(argc, argv, OPTIONS, long_options, &index);
    if (c == -1)
      break;
    switch (c) {
    case 0:
      break;
    case 's':
      shapeInfo = optarg;
      break;
    case 'i':
      inputValue = optarg;
      break;
    case 'l':
      lowerBound = optarg;
      break;
    case 'u':
      upperBound = optarg;
      break;
    case 'k':
      seed = atoi(optarg);
      break;
    case 'e':
#if !LOAD_MODEL_STATICALLY
      entryPointName = optarg;
#endif
      break;
    case 'n':
      sIterations = atoi(optarg);
      break;
    case 'm':
#ifdef _WIN32
      cout << "> Measurement option currently not available, ignore." << endl;
      break;
#endif
      sIterations = atoi(optarg);
      measureExecTime = true;
      break;
    case 'r':
      if (strcmp(optarg, "true") == 0) {
        reuseInput = true;
        printf("> Reuse input data\n");
      } else if (strcmp(optarg, "false") == 0) {
        reuseInput = false;
        printf("> Do not reuse input data\n");
      } else {
        printf("  reuse parameter expects true/false argument\n");
        usage(argv[0]);
      }
      break;
    case 'v':
      verbose = true;
      break;
    default:
      usage(argv[0]);
    }
  }
  if (sIterations < 1)
    sIterations = 1;

#if LOAD_MODEL_STATICALLY
  if (optind < argc) {
    cout << "Error: model.so was compiled in, cannot provide one now" << endl;
    usage(argv[0]);
  }
#else
  if (optind == argc) {
    cout << "Error: need one model.so dynamic library" << endl;
    usage(argv[0]);
  } else if (optind + 1 == argc) {
    loadDLL(argv[optind], entryPointName);
  } else {
    cout << "Error: handle only one model.so dynamic library at a time" << endl;
    usage(argv[0]);
  }
#endif
}

// =============================================================================
// Timing support.

#ifdef _WIN32
#else
struct timeval startTime, stopTime, result;
#endif

#ifdef _WIN32
inline void processStartTime() {}
inline void processStopTime() {}
#else
inline void processStartTime() {
  if (!measureExecTime)
    return;
  gettimeofday(&startTime, NULL);
}
inline void processStopTime() {
  if (!measureExecTime)
    return;
  gettimeofday(&stopTime, NULL);
  timersub(&stopTime, &startTime, &result);
  uint64_t time =
      (uint64_t)result.tv_sec * 1000000ull + (uint64_t)result.tv_usec;
  timeLogInMicroSec.emplace_back(time);
}
#endif

void printTime(double avg, double std, double factor, string unit) {
  int s = timeLogInMicroSec.size();
  int m = s / 2;
  printf("@time, %s, median, %.1f, avg, %.1f, std, %.1f, min, %.1f, max, %.1f, "
         "sample, %d\n",
      unit.c_str(), (double)timeLogInMicroSec[m] / factor,
      (double)(avg / factor), (double)(std / factor),
      (double)timeLogInMicroSec[0] / factor,
      (double)timeLogInMicroSec[s - 1] / factor, s);
}

void displayTime() {
  int s = timeLogInMicroSec.size();
  if (s == 0)
    return;
  sort(timeLogInMicroSec.begin(), timeLogInMicroSec.end());
  double avg = 0;
  for (int i = 0; i < s; ++i)
    avg += (double)timeLogInMicroSec[i];
  avg = avg / s;
  double std = 0;
  for (int i = 0; i < s; ++i)
    std += ((double)timeLogInMicroSec[i] - avg) *
           ((double)timeLogInMicroSec[i] - avg);
  std = sqrt(std / s);
  printTime(avg, std, 1, "micro-second");
  if (avg >= 1e3)
    printTime(avg, std, 1e3, "milli-second");
  if (avg >= 1e6)
    printTime(avg, std, 1e6, "second");
}

// =============================================================================

int main(int argc, char **argv) {
  parseArgs(argc, argv);

  // Get input signature from the model.
  const char *sigIn = OM_INPUT_SIGNATURE(entryPointName.c_str());
  if (!sigIn) {
    cerr << "Error: failed to get input signature for entry point '"
         << entryPointName << "'" << endl;
    return 1;
  }
  if (verbose) {
    cout << "Model Input Signature: " << sigIn << endl;
    const char *sigOut = OM_OUTPUT_SIGNATURE(entryPointName.c_str());
    cout << "Model Output Signature: " << (sigOut ? sigOut : "(empty)") << endl;
  }

  // Seed the RNG for reproducibility.
  omDefineSeed((unsigned int)seed, /*hasSeedValue=*/1);

  // Create input tensors with random data from the model's signature.
  OMTensorList *tensorListIn = omTensorListCreateFromInputSignature(
      sigIn,
      shapeInfo.empty()  ? nullptr : shapeInfo.c_str(),
      inputValue.empty() ? nullptr : inputValue.c_str(),
      lowerBound.empty() ? nullptr : lowerBound.c_str(),
      upperBound.empty() ? nullptr : upperBound.c_str(),
      verbose);
  if (!tensorListIn) {
    cerr << "Error: failed to create input tensors from signature" << endl;
    return 1;
  }

  cout << "Start computing " << sIterations << " iterations" << endl;
  for (int i = 0; i < sIterations; ++i) {
    processStartTime();
    OMTensorList *tensorListOut = RUN_MAIN_GRAPH(tensorListIn);
    processStopTime();
    if (tensorListOut)
      omTensorListDestroy(tensorListOut);
    if (i > 0 && i % 10 == 0)
      cout << "  computed " << i << " iterations" << endl;
    if (!reuseInput) {
      omTensorListDestroy(tensorListIn);
      tensorListIn = omTensorListCreateFromInputSignature(
          sigIn,
          shapeInfo.empty()  ? nullptr : shapeInfo.c_str(),
          inputValue.empty() ? nullptr : inputValue.c_str(),
          lowerBound.empty() ? nullptr : lowerBound.c_str(),
          upperBound.empty() ? nullptr : upperBound.c_str(),
          /*verbose=*/false);
    }
  }
  cout << "Finish computing " << sIterations << " iterations" << endl;
  displayTime();

  omTensorListDestroy(tensorListIn);
  return 0;
}
