theme: jekyll-theme-minimal
logo: /assets/img/onnx-mlir-logo.png
defaults:
  -
    scope:
      path: "ONNXAI.md"
    values:
      permalink: "index.html"

# Doxygen generated per-file doc references.
include: ["_*.html"]
