/*
 * SPDX-License-Identifier: Apache-2.0
 */

//===-------------------------- Accelerator.hpp ---------------------------===//
//
// Copyright 2022 The IBM Research Authors.
//
// =============================================================================
//
// Accelerator base class
//
//===----------------------------------------------------------------------===//

#pragma once

#include "include/onnx-mlir/Compiler/OMCompilerTypes.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/Pass/PassManager.h"
#include "llvm/ADT/SmallVector.h"

namespace onnx_mlir {
namespace accel {

// Note: this function is generated by cmake.
extern bool initAccelerators();

class Accelerator {
public:
  /// Kinds of accelerators.
  // Note: AcceleratorKinds.inc is generated by cmake.
  enum class Kind {
#define ACCEL_KIND(X) X,
#include "src/Accelerators/AcceleratorKinds.inc"
    NONE
#undef ACCEL_KIND
  };

  Accelerator(Kind kind) : kind(kind) {}
  virtual ~Accelerator() = default;

  /// Getter for the kind of this accelerator.
  Kind getKind() const { return kind; }

  /// Returns the set of accelerators available.
  static const llvm::SmallVectorImpl<Accelerator *> &getAccelerators();

  /// Returns whether the accelerator is active.
  virtual bool isActive() const = 0;

  /// Load the MLIR dialects necessary to generate code for an accelerator.
  virtual void getOrLoadDialects(mlir::MLIRContext &context) const = 0;

  /// Add the transformations necessary to support the accelerator.
  virtual void addPasses(mlir::OwningOpRef<mlir::ModuleOp> &module,
      mlir::PassManager &pm,
      onnx_mlir::EmissionTargetType &emissionTarget) const = 0;

  /// Register the MLIR dialects required to support an accelerator.
  virtual void registerDialects(mlir::DialectRegistry &registry) const = 0;

  /// Initialize the transformation passes required to generate code for an
  /// accelerator.
  virtual void initPasses(int optLevel) const = 0;

protected:
  static llvm::SmallVector<Accelerator *, 4> acceleratorTargets;
  /// Kind of accelerator.
  Kind kind;
};

} // namespace accel
} // namespace onnx_mlir
