name: build-docker-prereq-x86-nightly

on: 
  workflow_dispatch:
  pull_request:
    branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * SUN'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-llvm-nightly-x86-prereq-container:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: build a docker container for the latest llvm/mlir.
      env:
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      run: |
        # Build docker image for x86 arch, with the latest llvm/mlir & publish it.
        docker build --tag onnxmlirczar/onnx-mlir-llvmimage:x86 -f $GITHUB_WORKSPACE/.github/workflows/prereq.Dockerfile $GITHUB_WORKSPACE/utils
        docker login -u onnxmlirczar -p "$DOCKER_HUB_TOKEN" 
        docker push onnxmlirczar/onnx-mlir-llvmimage:x86
